### ISSUE TITLE
A list of banking app doesn't work

### ISSUE THREAD

**Issue by sdugoten** [jjolano/shadow#1]
Here is a list of banking app that doesn't work, it either crash on start, or hang on splash screen

HSBC HK Banking app
https://itunes.apple.com/us/app/hsbc-hk-mobile-banking/id1164066737?mt=8

HSBC Reward+
https://itunes.apple.com/hk/app/hsbc-hk-reward/id1315948639?l=en&mt=8

HSBC Payme
https://itunes.apple.com/us/app/payme-from-hsbc/id1184264977?mt=8

BEA banking app
https://itunes.apple.com/us/app/bea-%E6%9D%B1%E4%BA%9E%E9%8A%80%E8%A1%8C/id381215704?mt=8

Citibank HK banking app
https://itunes.apple.com/hk/app/citibank-hk/id373717372?l=en&mt=8

DBS banking app
https://itunes.apple.com/us/app/dbs-digibank-hong-kong/id1219200504?mt=8

Standard Chartered HK banking app
https://itunes.apple.com/us/app/sc-mobile-hong-kong/id445795688

**Comment by clirimks** [comment]
UBS Acces App crashes at lunch
https://itunes.apple.com/ch/app/ubs-access-connexion-s%C3%BBre/id1121666286?l=fr&mt=8

**Comment by jjolano** [comment]
Enabling dlsym hook (and maybe file map) seems to assist in some of these apps, but there are some bad side effects unfortunately. Not much I can do about it unless there is a way to stabilize the dlsym hook.
