### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by antoniozekic** [jjolano/shadow#10]
Hi, I'm having build errors and I'm not able to solve them even after trying every suggestion found on google...

Here's the output:

```
sers-Mac:shadow user$ make
> Making all for tweak 0Shadow…
==> Preprocessing Classes/Shadow.xm…
==> Compiling Classes/Shadow.xm (armv7)…
clang: error: no such sysroot directory: '' [-Werror,-Wmissing-sysroot]
make[3]: *** [/Users/user/GitHub/shadow/.theos/obj/debug/armv7/Classes/Shadow.xm.d9fe4f09.o] Error 1
rm /Users/user/GitHub/shadow/.theos/obj/debug/armv7/Classes/Shadow.xm.mm
make[2]: *** [/Users/user/GitHub/shadow/.theos/obj/debug/armv7/0Shadow.dylib] Error 2
make[1]: *** [internal-library-all_] Error 2
make: *** [0Shadow.all.tweak.variables] Error 2
Users-Mac:shadow user$ 
```

**Comment by jjolano** [comment]
According to this reddit post: https://www.reddit.com/r/jailbreakdevelopers/comments/91fbez/help_running_theos_on_maxos_mojave_beta/

You may be missing an SDK for theos. Place the 11.2 SDK from here: https://github.com/theos/sdks to $THEOS/sdks

**Comment by antoniozekic** [comment]
Thank you! It was successful! Do you mind explaining how to make a *.deb file?

**Comment by jjolano** [comment]
You can make a deb using `make package`.

**Comment by antoniozekic** [comment]
Thank you!
