### ISSUE TITLE
Device won't boot to userspace

### ISSUE THREAD

**Issue by perxia** [jjolano/shadow#101]
Atter updating to 3.6.0 or above (3.5.6 works fine), if I do a userspace reboot the device fails to reload and panics.  When booting with checkra1n, springboard won't load and eventually reboots. Tried disabling all tweaks in iCleaner except shadow and it still happens. The only way to boot successfully is to boot into either stock or safemode.

iPhone X 14.8.1 checkra1n (Substrate)

Here is the panic log : 
https://pastebin.com/sDD7de9N

**Comment by jjolano** [comment]
Likely related to the injection changes from 3.6.0. You are running actual Cydia Substrate? or is it Substitute?

Something to try is editing `/Library/MobileSubstrate/DynamicLibraries/Shadow.plist` and changing `com.apple.Foundation` to `com.apple.UIKit`. This reverts the injection change in 3.6.0 but will be overwritten by updates. I may also consider reverting the change for the next update.

**Comment by perxia** [comment]
I'm running actual Cydia Substrate. Changing the filter to UIKit now works fine. Thank you!

**Comment by jjolano** [comment]
fixed for 3.6.2
