### ISSUE TITLE
Most App Crashes

### ISSUE THREAD

**Issue by budakcivic** [jjolano/shadow#102]
Working fine with previous version 3.6.1. While with same setup on 3.6.2, most my apps with shadow turned on crashed immediate (force close). Reverted back to 3.6.1.

**Comment by budakcivic** [comment]
Sorry cant provided the crash reporter since not support for Xina Jailbreak. I have 12 apps using shadow to avoid jailbreak detection but with shadow version 3.6.4 all apps can run back except 1 that is shopee https://apps.apple.com/my/app/shopee-my-2-2-jimat-giler-sale/id959841113 still unable to open. Only version 3.6.1 can solve the issue with option Runtime Symbol Lookups have to disable. At the moment reverted back to 3.6.1 is the best option. Mine jailbreak XinaA15 ios15.1.1 iphone 13 pro max

**Comment by jjolano** [comment]
Sorry, I have chosen not to offer support for Xina. The fact that tweaks have completely broken in the past by updating the jailbreak as well as the lack of useful crash logs makes it a pain to try and support.
