### ISSUE TITLE
Working bypass for TikTok

### ISSUE THREAD

**Issue by keychain2db** [jjolano/shadow#106]
Greetings, I am currently using Taurine on iOS 14.3 and it seems like Shadow version 3.6.2-12+debug (3.6.2 does not work, only the debug ones do) is among one of the only ones which currently work for this app, nevertheless, I am currently unable to get the .deb file since it has been taken down from [your repo](https://ios.jjolano.me/me.jjolano.shadow.beta_3.6.2-12+debug_iphoneos-arm.deb), may I please get a copy of it if you still have it? Thank you

**Comment by jjolano** [comment]
Here is a direct link: https://github.com/jjolano/ios-repo/raw/5f9266615b1a3529c7583558f4b67a585fe8fc73/me.jjolano.shadow.beta_3.6.2-12%2Bdebug_iphoneos-arm.deb

**Comment by keychain2db** [comment]
Oddly enough they seem to not work anymore, thank you for your help anyway
