### ISSUE TITLE
Bank app help needed 

### ISSUE THREAD

**Issue by tongcheung0218** [jjolano/shadow#107]
Dear Development:
I tried several settings but I’m not able to make this app working…

https://apps.apple.com/cn/app/%E5%B7%A5%E9%93%B6e%E7%94%9F%E6%B4%BB-%E7%BE%8E%E5%A5%BD%E7%94%9F%E6%B4%BB%E8%A7%A6%E6%89%8B%E5%8F%AF%E5%8F%8A/id1044166783

my shadow version is 3.6.4 (Lastest  Beta Version),and here's my settings

![IMG_0376](https://user-images.githubusercontent.com/52878692/218316155-5713b275-0a28-49bb-a78e-1f52438f7c5c.PNG)
![IMG_0377](https://user-images.githubusercontent.com/52878692/218316165-edb7a2a9-2160-456b-b4ed-353737a6c786.PNG)

i'm looking forward to you can fix it, thank you!

**Comment by tongcheung0218** [comment]
i turned on some options but it doesn't work and i turned all options ,it still doesn't work.

**Comment by tongcheung0218** [comment]
Xina Version 1.1.6.2,
iOS 15.0.1 
iPhone 13 Pro Max,

**Comment by jjolano** [comment]
Did you try using `fishhook` for the hooking library?

**Comment by tongcheung0218** [comment]
Yes,I tired to use fishhook mode but it still doesn’t work.

**Comment by jjolano** [comment]
Try again with the latest version. If it still doesn't work, it's probably an issue with Xina.

**Comment by tongcheung0218** [comment]
I think this bank app checked some jailbreak methods but i don’t know how can hide it. Because it runs on LinTui Mode with Xina.

**Comment by jjolano** [comment]
If that works, then I suggest to use that. I can't offer much help for Xina.
