### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by wwpp3399** [jjolano/shadow#11]
➜  shadow-master make
Makefile:4: /makefiles/common.mk: No such file or directory
Makefile:11: /tweak.mk: No such file or directory
Makefile:16: /aggregate.mk: No such file or directory
make: *** No rule to make target `/aggregate.mk'.  Stop.

Please help me,thanks

**Comment by jjolano** [comment]
Building this project requires theos. It seems you don't have theos installed. Please follow the instructions here to install theos: https://github.com/theos/theos/wiki/Installation
