### ISSUE TITLE
[Bug] Regression on 3.6.7

### ISSUE THREAD

**Issue by LileAuTresor** [jjolano/shadow#110]
Some apps detect jailbreak on Shadow 3.6.7 but not on 3.6.4 :

 - iOS Version: 13.5
 - Jailbreak: Unc0ver
 - Shadow version: 3.6.7
 - Affected apps (App Store links):
Doctolib : https://apps.apple.com/fr/app/doctolib/id925339063
Paiement mobile : https://apps.apple.com/fr/app/paiement-mobile-ca/id1038067309
 - Relevant Shadow options, if any: fishhooks with essential and recommanded hooks works on 3.6.4. Nothing works on 3.6.7 whatever hooks checked

**Comment by jjolano** [comment]
Unable to confirm on Taurine 14.3.. I will check with palera1n later.

Are you able to run some commands over ssh and transfer some files?

Will need these commands run and file uploaded here: `find /usr | xargs shdw > shdw_usr.txt` and `find /var | xargs shdw > shdw_var.txt`

Files: shdw_var.txt and shdw_usr.txt 

These commands may take a while to run, so keep your screen awake.

**Comment by AK-47v** [comment]
I didn’t have any problems with shadow on xina 15  this is the best jailbreak detection tweak forever it’s working with pubg mobile without problems but when i update shadow to the last update 3.6.7yesterday when i open pubg it keeps crashing but when i choose from hooking library fishhook or dobby its work normally without crash but if i leave it on automatically its keep crashing not just pubg its crashing with all app it seems the automatic hooking doesn't work

**Comment by LileAuTresor** [comment]
[shdw_var.txt](https://pastebin.com/WFvTQWp8)
[shdw_usr.txt](https://pastebin.com/MddDNVqY)

Tell me if it's what you need.

Thanks !

**Comment by jjolano** [comment]
Seems the /var one wasnt working. Try with `find /private/var | xargs shdw > shdw_var.txt` instead

**Comment by LileAuTresor** [comment]
[shdw_var.txt v2](https://www.dropbox.com/s/v7ztd6nxdycvzr2/shdw_var.txt?dl=0)

Download on dropbox (8Mo)

**Comment by jjolano** [comment]
See if the beta improves this. Also, if you can sideload this IPA to test detection, would be helpful to know the results for `Bastille` under fishhook and automatic. https://github.com/jjolano/EffulgenceDemo/releases/tag/v2.3

**Comment by LileAuTresor** [comment]
It doesn’t work on shadow beta 3.6.8.2, still jailbreak detection. I can’t test Effulgencedemo 2.3 because it needs iOS 14 and I’m on 13.5...

**Comment by jjolano** [comment]
How about this version? https://github.com/jjolano/EffulgenceDemo/releases/tag/v1.0

**Comment by LileAuTresor** [comment]
With version 1 of Effulgence :
Fishhooks : no artifacts detected
Automatic : runtime modification detected

**Comment by jjolano** [comment]
Thats the expected result. Just pushed an update to the beta. See if any difference

**Comment by LileAuTresor** [comment]
It works, thanks !

I tested this beta version on all my apps, everything works except one that crashes. I will open another issue for this.
