### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by AK-47v** [jjolano/shadow#112]
**Describe the bug**

**To Reproduce**
1. Go to 'shadow'
2. Click on ‘application '
3. Scroll down to 'an app & go to hooking library '
4. See error  seems to be automatic hook doesn’t work in last update 3.6.7 

**Expected behavior**

I didn’t have any problems with shadow on xina 15 this is the best jailbreak detection tweak forever it’s working with pubg mobile without problems but when i update shadow to the last update 3.6.7yesterday when i open pubg it keeps crashing but when i choose from hooking library fishhook or dobby its work normally without crash but if i leave it on automatically its keep crashing not just pubg its crashing with all app it seems the automatic hooking doesn't work

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version: 15.1
 - Jailbreak:xina A15
 - Shadow version:3.6.7
 - Affected apps (App Store links):all apps 
 - Relevant Shadow options, if any:

**Additional context**
Please try to make shadow work with  8 ball pool game its keep crashing

**Comment by jjolano** [comment]
I am not supporting Xina. I literally cannot test anything for it. I suggest downgrading to whatever version is working or just use fishhook.
