### ISSUE TITLE
[Bug] Crashlog app EDF et Moi (shadow beta 3.6.8-3)

### ISSUE THREAD

**Issue by LileAuTresor** [jjolano/shadow#113]
Hi,
If you can look, i have one last app that doesn't work with Shadow (tested on latest beta version 3.6.8-3) : with fishhooks library and all hooks checked the application crash ([crashlog](https://www.dropbox.com/s/2yc2yitgd39ih6z/stacks%2BEDFetMoi%20Prod-2023-02-16-182401.ips?dl=0)). If I only check essentials and recommended hooks the application opens but freezes (no access to graphics etc).
![IMG_1865](https://user-images.githubusercontent.com/42318092/219445812-0ef757bf-f6e6-4fe4-a11d-e0d7285fe8b9.jpg)

For information A-Bypass works on this application.

 - iOS Version: 13.5
 - Jailbreak: unc0ver
 - Shadow version: 3.6.8-3 (beta)
 - Affected apps (App Store links): https://apps.apple.com/fr/app/edf-moi/id563799142

Tell me if you want i test something.

Thanks !

**Comment by jjolano** [comment]
Can you try disabling one option at a time until it works? Unless the option is necessary for detection.

**Comment by LileAuTresor** [comment]
You were right, it works with only essential hooks checked. 
All my apps work, you are the best !

**Comment by LileAuTresor** [comment]
Yes, foundation framework with essential hooks freeze the app. 
The app crashes if I check essential framework + detection framework + foundation framework

**Comment by jjolano** [comment]
Thanks, I'll take a look. Issue solved for now at least.
