### ISSUE TITLE
Uses different UI randomly

### ISSUE THREAD

**Issue by WillXProject** [jjolano/shadow#114]
Unsure how to replicate, but Shadow’s UI in settings changes randomly, and instead seems to use AppList instead of AltList

**Comment by jjolano** [comment]
Could be a remnant of legacy Shadow (v2.x). AppList was dropped completely with version 3.

Try the following: 
- Uninstall Shadow
- Install Shadow (legacy)
- Uninstall Shadow (legacy)
- Reinstall Shadow
