### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by keinengel** [jjolano/shadow#116]
**Describe your idea. Include drawings or screenshots if necessary.**
[...]
Hi, first of all I want to thank you hard work

I wonder if you accept requests? I'm from Brazil and many main bank apps are blocked on my iPhone 11 (ios 14,7 uncover jb). Tried to use shadow and didnt work

apps: Itaú, C6 Bank, XP Investimentos

thank you so much

**Comment by jjolano** [comment]
I do not accept any requests as Shadow is not designed for anything app-specific.
