### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by R1p4eg** [jjolano/shadow#118]
Thank you for the awesome work! 

It would be nice feature to configure settings of the Shadow through some config-file or manually from command line (from ssh for example). May be this is already implemented, but I cant find any docs or examples for this. 

This feature could be nice to automate some everyday tasks for security researchers, that have their own automation for detecting vulns in apps. 

Thank you again :)

**Comment by jjolano** [comment]
Currently not implemented but it's a good idea for that specific use case. If you are able to edit plist files (either on-device with a tool or download+re-upload), you can check the config file at `/var/mobile/Library/Preferences/me.jjolano.shadow.plist`.

**Comment by R1p4eg** [comment]
Thanks for the quick answer!

I think that is exactly what I needed, but after re-uploading modified plist file nothing happened (also try to respring). 

What should I do after changing values in this file or re-upload it to use new settings?

**Comment by R1p4eg** [comment]
Oh, thats works!

Thank you so much!

**Comment by jjolano** [comment]
Seems like the `defaults` command might be the best tool here for this purpose. There is a package on Procursus, or included with Cephei.
