### ISSUE TITLE
Problem with Frameworks update

### ISSUE THREAD

**Issue by D1mar0n** [jjolano/shadow#119]
**Describe the bug**
After today's Frameworks update, CallBar by Limneos stopped working.

**Device Information (please complete the following information):
- iDevice:  iPhone 12 Pro
- iOS: 14.2
- Jailbreak: Taurine 1.1.6
 - Shadow version: 3.6.9

![A78AF47E-42AC-4E75-AF2B-25D3FCB5C83E](https://user-images.githubusercontent.com/35725771/227841605-ef1b85de-f6bb-4fb5-bb34-42f79ddc3a59.jpeg)

**Comment by jjolano** [comment]
Not sure what this has to do with Shadow, but tweaks would not be directly affected by framework updates. Especially if they don't even use said frameworks.

As for the updates, they are just a recompile with a different toolchain to prepare for rootless. Nothing more. The only tweak affected as far as I know is Shadow, and it only operates within apps.

**Comment by D1mar0n** [comment]
Thanks for the answer. It seemed to me very strange, since I perfectly understand that these updates have no direct relation to CallBar. What could happen? - I don't understand... I'll try to figure it out on my own.

Unfortunately, PayPal Business does not start with Shadow and CaixaBank Sign still does not start. I really hope that with future updates these applications will still start working, only hope is on you. Because otherwise you will have to abandon Jailbreak.

All the best and thank you for Shadow.
На Пн.27.03.2023 7:10:14, jjolano ***@***.***> написал(а):
Not sure what this has to do with Shadow, but tweaks would not be directly affected by framework updates. Especially if they don't even use said frameworks.
As for the updates, they are just a recompile with a different toolchain to prepare for rootless. Nothing more. The only tweak affected as far as I know is Shadow, and it only operates within apps.

**Comment by jjolano** [comment]
latest update reverts compiling method for rooted builds - should be fixed

**Comment by D1mar0n** [comment]
Hello! Thank you very much for your message.CaixaBank Sign, PayPal Business and 8 Ball Pool not works...
На Вт.28.03.2023 5:14:15, jjolano ***@***.***> написал(а):
latest update reverts compiling method for rooted builds - should be fixed

**Comment by D1mar0n** [comment]
Hello! I'm sorry to bother you with my questions, but could you tell me: should I manually install all the Frameworks?

 
На Вт.28.03.2023 6:40:37, Dima Ivanov ***@***.***> написал(а):
Hello! Thank you very much for your message.CaixaBank Sign, PayPal Business and 8 Ball Pool not works...
На Вт.28.03.2023 5:14:15, jjolano ***@***.***> написал(а):
latest update reverts compiling method for rooted builds - should be fixed

**Comment by jjolano** [comment]
It should automatically install all necessary frameworks for Shadow whenever updating or first installing. Usually you don't have to manually install them.

**Comment by D1mar0n** [comment]
Thank you very much for your answer. I only asked because I do not have the Frameworks listed in the screenshot installed, and in the "Hooking Library" settings there are only "Automatic" and "Cydia Substrate", although I have Jailbreak "Taurin". Maybe I should uninstall everything and reinstall?
На Пн.03.04.2023 0:36:34, jjolano ***@***.***> написал(а):
It should automatically install all necessary frameworks for Shadow whenever updating or first installing. Usually you don't have to manually install them.
