### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by onlynair** [jjolano/shadow#120]
Problem with Frameworks update

**Comment by onlynair** [comment]
Describe the bug
After today's Frameworks update, CallBar by Limneos stopped working.

**Device Information (please complete the following information):

iDevice: iPhone 11
iOS: 13.6
Jailbreak: Odyssey 1.4.1
Shadow version: 3.6.9
![image](https://user-images.githubusercontent.com/78968666/228096194-4becc4f9-38f0-4a68-b5a1-05ad31a3e544.jpeg)

**Comment by jjolano** [comment]
latest update reverts compiling method for rooted builds - should be fixed
