### ISSUE TITLE
99% cpu load on process called shadw

### ISSUE THREAD

**Issue by defeusers** [jjolano/shadow#121]
I just downgrade from 3.7.1 and no more shadw process full load

**Comment by jjolano** [comment]
That shouldnt normally happen. How many tweaks/packages do you have installed?

**Comment by defeusers** [comment]
About 20 tweak but nothing wrong before update shadow to 3.7.1,i repeat that only shadw process make my phone hot like a oven it used all my remaining cpu usage
Please take a look shadow is a greatest jbhider in my entire decade of using tweaks
Thanks jjolano

**Comment by defeusers** [comment]
![F904C8EB-5E5D-4404-A393-F660A51B53FE](https://user-images.githubusercontent.com/71370726/228630336-648b9121-f535-4bad-9954-4f0a9f6c4fff.png)
![DF650B3D-7830-4CF9-89CB-F517781AA5F3](https://user-images.githubusercontent.com/71370726/228630374-c5f2f87e-4e27-4287-9b9a-86c585440bd0.png)
Install using zebra it stuck at shadw! Then phone starting to full load by shadw process,then it broke my downgrade,i have to kill the process and downgrade
Im using uncover on ios 14.8 11prm

**Comment by jjolano** [comment]
Looks like an issue with internal shadow database generation. I will have a look for next update.

**Comment by jjolano** [comment]
If the next update fixes the issue, you can close the issue. For now leave it open
