### ISSUE TITLE
Issus in setting - shadow

### ISSUE THREAD

**Issue by Efrayyy** [jjolano/shadow#122]
There was an error loading the preference bundle for
Shadow: The bundle "ShadowSettings.bundle" couldn't
be loaded
Hide Details
dlopen(/private/preboot/
95B2B3A3801819807E165B03C3E453661CFE9DEF08D
4DA92DBF940C5D49672BF3A6D921ABF24B84263FC6
ED3FEB80A71/jb-4UGnB9/procursus/Library/
PreferenceBundles/ShadowSettings.bundle/
ShadowSettings, 0x0109): Library not loaded: @rpath/
Modulous.framework/Modulous
Referenced from: /private/preboot/
95B2B3A3801819807E165B03C3E453661CFE9DEF08D
4DA92DBF940C5D49672BF3A6D921ABF24B84263FC6
ED3FEB80A71/jb-4UGnB9/procursus/Library/
Frameworks/HookKit.framework/HookKit
Reason: tried: '/var/ib/Library/Frameworks/
Modulous.framework/Modulous' (no such file), '/var/jb/
usr/lib/Modulous.framework/Modulous' (no such file), "
var/jb/Library/Frameworks/Modulous.framework/
Modulous' (no such file), '/var/ib/usr/lib/
Modulous.framework/Modulous' (no such file), '/Library/
Frameworks/Modulous.framework/Modulous' (no such
file), '/var/jb/Library/Frameworks/Modulous.framework/
Modulus' (no such file), '/usr/lib/Modulous.framework/
Modulous' (no such file), '/var/jb/usr/lib/
Modulous.framework/Modulous' (no such file), '/var/jb/
Library/Frameworks/Modulous.framework/Modulous'(no
such file), '/var/jb/usr/lib/Modulous.framework/
Modulous' (no such file), '/Library/Frameworks/
Modulous.framework/Modulous' (no such file), '/var/ib/
Library/Frameworks/Modulous.framework/Modulous'(no
such file), '/usr/lib/Modulous.framework/Modulous'(no
such file), '/var/jb/usr/lib/Modulous.framework/
Modulus' (no such file), '/Applications/Preferences.app/

**Comment by Efrayyy** [comment]
In settings/shadow this issue coming 
What i will do 3.7.2 ver

**Comment by Efrayyy** [comment]
Fugu15 max ios 15.3.1

**Comment by jjolano** [comment]
Is Modulous Framework not installed? The log says it isn't found..

**Comment by Efrayyy** [comment]
Yes i installed

**Comment by Efrayyy** [comment]
I reinstalled Modulous Framework and working thnx 🙏
