### ISSUE TITLE
"中国建设银行" App not working

### ISSUE THREAD

**Issue by l1Dan** [jjolano/shadow#124]
**Describe the bug**
"中国建设银行" App not working

**To Reproduce**
-

**Expected behavior**
-

**Screenshots**

![1941680943200_ pic](https://user-images.githubusercontent.com/7961100/230712303-f2013ccd-d440-4a36-94ea-b00e4d2cb375.jpg)
![1931680943200_ pic](https://user-images.githubusercontent.com/7961100/230712307-de56ee83-bf13-4554-bfc6-6957bff84e11.jpg)

**Device Information (please complete the following information):**
 - iOS Version: 15.4.1
 - Jailbreak:  Fugu15 Max
 - Shadow version: 3.7.2
 - Affected apps (App Store links): https://apps.apple.com/us/app/%E4%B8%AD%E5%9B%BD%E5%BB%BA%E8%AE%BE%E9%93%B6%E8%A1%8C/id391965015?l=zh
 - Relevant Shadow options, if any:

**Additional context**

**Comment by jjolano** [comment]
You need to enable more hook options. Start by enabling the options under Essential and trying again.

**Comment by l1Dan** [comment]
This same problem
https://user-images.githubusercontent.com/7961100/230753314-3b3af91e-80a2-47a8-8a17-936c6257f7a4.MOV

**Comment by jjolano** [comment]
You can try other hooking library and enabling more hook options. That's about all I can suggest - if it still doesn't work, then you just have to wait for updates that will support more bypass methods.

**Comment by l1Dan** [comment]
You did a great job, work fine.
![image](https://user-images.githubusercontent.com/7961100/230782644-2581f8f6-def2-4ea4-8894-27e01ac9fc13.png)
