### ISSUE TITLE
[Feature Request] OPT Bank

### ISSUE THREAD

**Issue by MrHumanRebel** [jjolano/shadow#126]
Hi!

The "OPT Bank"  and "Simple" (also by OTP) applications are crashing or detecting JB. I tried all the extra hooks, no luck so far. 
Would you take a peek at these apps? Would be nice to be able to use them.

Thanks in advance!

URL_1: https://apps.apple.com/hu/app/otp-bank-hu/id1403268557
URL_2: https://apps.apple.com/hu/app/simple-vedd-egyszer%C5%B1en/id819236628

<img src='https://user-images.githubusercontent.com/80947401/230790241-bf247287-29e4-4cfb-861a-73af92ada24c.png' width='200'>
<img src='https://user-images.githubusercontent.com/80947401/230790411-8d612ab4-14e4-4907-99c6-cd9c03bb4ebd.png' width='200'>

**Comment by jjolano** [comment]
I won't be looking into these, to be honest. There are still more detection methods to implement a bypass against in future updates, and even then its not guaranteed to be successful. Best bet for now is an app-specific bypass - something that Shadow is not designed for.
