### ISSUE TITLE
[Request] Please add support for below Banking app.

### ISSUE THREAD

**Issue by mkint0x** [jjolano/shadow#127]
App in question is [UBL Digital UAE](https://apps.apple.com/ae/app/ubl-digital-uae/id1474048311). Shadow tweak used to bypass this Banking app's version 1.0.7. But above 1.0.7, Not just Shadow, no tweak could bypass the apps JB Detection. Please add bypass for this app.

**Comment by jjolano** [comment]
I don't "add bypasses" for apps. I add bypass methods. There is a difference and is the reason why the tweak is designed to work against majority of detection.

I suggest you downgrade your version of the app, or use other methods (as specified in the readme)
