### ISSUE TITLE
[Feature Request] iOS 16 Supported ?

### ISSUE THREAD

**Issue by Chensem** [jjolano/shadow#130]
install from zebra will encounter problems like below
```
Package is designed for rootless jailbrekas, but your devices is using a non-rootless or incorrectly configured jailbreka
```

**Comment by jjolano** [comment]
You should use sileo nightly if you are on a rootless jailbreak.

**Comment by Chensem** [comment]
but i think my device is using rootless jailbreak , because only sileo installed on my device , not sileo nightly 
my device environment 
```
iphone 8
ios : 16.3.1
```

**Comment by Chensem** [comment]
i use the following commands to jailbreak my device
```
./palera1n-macos-universal -cf
./palera1n-macos-universal -f
```

then install the dependence from palera1n

**Comment by Chensem** [comment]
solved it , using `palera1n -l` rootless jailbreak

**Comment by Chensem** [comment]
i installed it successfully , but i can't find the config item at Settings APP ? any solution ?

**Comment by Chensem** [comment]
![image](https://user-images.githubusercontent.com/27469499/232235841-dec74624-70be-4cd3-b0e2-65a3645f9cb5.png)

**Comment by jjolano** [comment]
Make sure you have a rootless version of preferenceloader.

**Comment by Chensem** [comment]
done , reinstall sileo
