### ISSUE TITLE
Brubank app v1.75.0 crashes with Shadow v3.7.3 on iOS 14.3 using Taurine

### ISSUE THREAD

**Issue by leandroprz** [jjolano/shadow#133]
[Brubank app](https://apps.apple.com/us/app/brubank-banco-digital/id1295202448) was working fine for me up to v1.70.3, but every single update after that (including the latest) is crashing on my 6s.

Here are a few Cr4shed logs:
- https://pastebin.com/2KbpaW7W
- https://pastebin.com/PYbcmZVZ
- https://pastebin.com/KgYrC0aM

**Device Information (please complete the following information):**
 - iOS Version: 14.3
 - Jailbreak: Taurine
 - Shadow version: 3.7.3
 - Affected apps (App Store links): [Brubank](https://apps.apple.com/us/app/brubank-banco-digital/id1295202448)
 - Relevant Shadow options, if any: I have everything enabled except the options under "Dangerous hooks". I tried enabling all of them one by one, but had no luck.

**Additional context**
I tried A-Bypass, vnodebypass and opening the app when not jailbroken, but the app still crashes.

**Comment by jjolano** [comment]
So updating the app started crashes or updating Shadow started crashes? If its the former, I can only recommend that you downgrade the app because that sounds like updated detection methods, as mentioned in the readme.

**Comment by leandroprz** [comment]
Updating the app started crashes. I'm currently using an older version of the app, but I was hoping a new detection method could be implemented in Shadow to avoid the crashes.
