### ISSUE TITLE
[Bug] Crashes after opening the app

### ISSUE THREAD

**Issue by maskkit** [jjolano/shadow#134]
**Describe the bug**
Crashes after opening the app

**To Reproduce**
1. Go to 'donwnload https://apps.apple.com/cn/app/id454685734'
2. Click on 'App'
3. App crash

**Device Information (please complete the following information):**
 - iOS Version:  14.7.1
 - Jailbreak: yes
 - Shadow version: v3.7.3
 - Affected apps (App Store links): https://apps.apple.com/cn/app/id454685734
 - Relevant Shadow options, if any:
   1. All settings combinations are tested, but still crash
   2. Multiple versions of shadow have also been tested
   3. Multiple versions of framework have also been tested

**Comment by jjolano** [comment]
This isnt a Shadow bug.
