### ISSUE TITLE
Some app not working after the new update [Bug] 

### ISSUE THREAD

**Issue by hs200085** [jjolano/shadow#137]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version: 15.1
 - Jailbreak: Dopamine
 - Shadow version: 3.7.4
 - Affected apps (App Store links): https://apps.apple.com/us/app/kfc-bahrain/id1534102692
 - Relevant Shadow options, if any:

**it was not detecting the jailbreak on the previous version of shadow*

**Comment by jjolano** [comment]
Likely preferences loading code. Stay tuned for 3.7.5

**Comment by hs200085** [comment]
Solved thank you so much
