### ISSUE TITLE
Clash of Clans Not Working With shadow

### ISSUE THREAD

**Issue by AhmedSaleem0667** [jjolano/shadow#139]
Clash of Clans crashed on Jailbroken devices please Help !!

**Comment by K1llah03z** [comment]
Use choicy!! It bypassed it

**Comment by AhmedSaleem0667** [comment]
Not working anymore after the New update of Clash of clans

**Comment by AhmedSaleem0667** [comment]
![Uploading 239907127...]

**Comment by AhmedSaleem0667** [comment]
![image](https://github.com/jjolano/shadow/assets/58516208/6181c352-9807-42a6-918e-8c4880b5b8a8)

**Comment by AhmedSaleem0667** [comment]
are u using palera1n Jailbreak or Dopamine
