### ISSUE TITLE
Aetna Mobile Jailbreak Detection

### ISSUE THREAD

**Issue by ccsasuke** [jjolano/shadow#14]
Great tweak! Worked really well for most of my apps.
The one exception is: Aetna Mobile
https://apps.apple.com/us/app/aetna-mobile/id380845816

None of the jb detection bypass tweaks I have used could get me into this app, including Shadow. I'm wondering if it is using some overlooked technique to detect jb.
It would be great if you can take a look. Thanks!

**Comment by jjolano** [comment]
Looks like it's using KonyLabs' jailbreak detection library. Quite a strong detection they have, and may need to be specifically targeted to bypass it (and all apps that use this library as well).

**Comment by KH12** [comment]
Can bypass it on future update shadow ?
