### ISSUE TITLE
Bypass YouBRD bank app Romania

### ISSUE THREAD

**Issue by remusici** [jjolano/shadow#147]
Hello. Can you please help me to bypass YouBRD app? Is a Romanian bank app. I have iPhone 11 pro MAX on 14.3 jailbreaked with Unc0ver v 8.0.2. I tryed all hooks but none seems to work. Help would be appreciated. Thanks in advance

**Comment by ghost** [comment]
since you're on iOS 14.3 you can try KernBypass or vnodebypass

**Comment by remusici** [comment]
> since you're on iOS 14.3 you can try KernBypass or vnodebypass 

I already tryed both but they don't work. 
Shadow worked before till last update of the bank app. 
Now i installed Hestia , i enabled some hooks and i managed to Open the app. BTW It takes long time to Open. Shadow opened the app faster before last update of the bank app. 
Now i can open the app but i can't register anymore. I can't pass of the Foto verification. I can do the foto but when i press to Upload, it keeps loading forever and says "upload of the foto in course".
It is another method to verify my identity but only in the bank. I will go monday in the bank and i let you know if i solved

**Comment by remusici** [comment]
Solved! I have just downgraded Shadow from 3.7.6 to 3.7.5. Looks like 3.7.6 is not working well on 14.3. 
Anyway Thanks for your great work jjolano. God bless you!
🤝🤝🤝
