### ISSUE TITLE
[Bug] DNSCloak can't be launched normally it just crash.

### ISSUE THREAD

**Issue by i1itione** [jjolano/shadow#158]
**Describe the bug**
The app just crash when device is jailbroken.

**To Reproduce**
Just need opening DNSCloak then it is crashed immediately.

**Expected behavior**
The app will be used normally, just like device at un-jailbroken status.

**Device Information (please complete the following information):**
 - iOS Version: 16.5.1
 - Jailbreak: palen1x v1.1.0 (palera1n-c beta 7)
 - Shadow version: 3.7.6
 - Affected apps (App Store links): https://apps.apple.com/us/app/dnscloak-secure-dns-client/id1452162351
 - Relevant Shadow options, if any: All enabled for it (per app mode not global).

**Additional context**
I also tried using Choicy (Shadow disabled of course) to disable load any tweak to DNSCloak but doesn't work either.

**Comment by jjolano** [comment]
Not a bug.
