### ISSUE TITLE
Q: Is it possible to bypass the Shadow Jailbreak bypass?

### ISSUE THREAD

**Issue by LyuboFromTryzens** [jjolano/shadow#168]
As an iOS developer for 10 years, I am new to the art of jailbreak. Given the methods of jailbreak detection (cydia scheme, system folder access, etc.), I am trying to understand is there a way to detect Shadow? I am fully aware of the purpose of Shadow, but following the Newton's Third Law, I am always looking for the opposite reaction.

**Comment by saudgl** [comment]
Are you mentally fit to make such a request here?

**Comment by LyuboFromTryzens** [comment]
> Are you mentally fit to make such a request here?

Apparently not as little as you are, given the disrespectful comment.
