### ISSUE TITLE
Bertha Jailbreak Detection

### ISSUE THREAD

**Issue by TheNoim** [jjolano/shadow#17]
Could you please look into Bertha by Mercedes Benz (https://apps.apple.com/de/app/bertha-deine-tank-app/id1427658183) Shadow doesn't seem to do anything there.

**Comment by jjolano** [comment]
Unfortunately this app is not available in my region. What happens when you launch the app? Also, have you tried enabling Lockdown Mode (and maybe filtering dynamic linker)?

**Comment by TheNoim** [comment]
I tried every setting of shadow and reinstalled the app always, to make sure the app does not save anything related to the "block". Also I checked whether the app checks if the device is blacklists. However, it doesn't do any request to a server while launching. I am not experienced enough in reverse engineering to bypass the detection by myself. I had no luck with class dump or frida. There is a jailbreak related class, but it is empty. I could extract the ipa for you and send it over. 

![image](https://user-images.githubusercontent.com/5133056/62279057-9fe97400-b449-11e9-832a-3825508a5832.png)

**Comment by jjolano** [comment]
Sure, if you can decrypt the app and send it I can have a look.

**Comment by TheNoim** [comment]
I already decrypted it. Where should I send it? I don’t think it is a good idea to upload it public and post it here.

**Comment by jjolano** [comment]
Send me a link via DM on reddit: https://www.reddit.com/user/jjolano
