### ISSUE TITLE
Verbose banking app

### ISSUE THREAD

**Issue by legendaryApps** [jjolano/shadow#18]
Hey,
There is yet another banking app, that crashes upon startup: https://apps.apple.com/ch/app/postfinance-mobile/id386766642
Since the app crashes right-away, it can't be decrypted.
If "Enable standard filters" is disabled, it logs "found 3rd party dylib /Library/MobileSubstrate/MobileSubstrate.dylib" before crashing
When enabled, it logs "duplicated dylib /.file"

Sometimes it also logs "there are more dynamic libs than the number reported by _dyld_image_count()"

No measures got me past the "duplicated dylib /.file" error and then crash.

Do you think you can help?

**Comment by jjolano** [comment]
Interesting. Seems that it's actually checking and keeping track of loaded dylibs to find out if there's something hiding it (in this case, Shadow).

It's possible to fix this, though probably at a performance cost on startup. I'll see what I can do for the next version.

**Comment by legendaryApps** [comment]
Great! If I can be of any help, let me know. Also if you know any way of decrypting an app that crashes on startup (hooking exit function?), I can try it out.

**Comment by legendaryApps** [comment]
Do you have any news and can I be of help in any way?
