### ISSUE TITLE
VR-Banking not working

### ISSUE THREAD

**Issue by zippoking** [jjolano/shadow#21]
Hi there,

recently i updated my iPhone 6s from 11.3.1 to 12.4 and jailbroke with unc0ver.
I am trying to get my bank app working, but so far i have no luck.

Would be awesome if you could confirm that it is really not working and not because i am using wrong settings.

Here are the bank details:
VR-Banking von Fiducia & GAD IT AG https://apps.apple.com/de/app/vr-banking/id375341021

Thanks in advance.
Best Regards
Zippoking

**Comment by TheNoim** [comment]
Just a quick note: Most german banking apps use the Promon Shield jailbreak detection. Defeating this would also defeat most other banking apps.
