### ISSUE TITLE
Checkra1n and iOS 13

### ISSUE THREAD

**Issue by TheNoim** [jjolano/shadow#26]
Hey,

Do you have plans to update Shadow for iOS 13?

**Comment by DrConflict** [comment]
I second this. Shadow is crashing on startup sadly.

**Comment by jjolano** [comment]
From what I heard, it's a dependency issue with Cephei since it's not updated. I will eventually be updating Shadow, just haven't had the time due to real life.

**Comment by jjolano** [comment]
An update to Cephei was released, and Shadow preferences now work correctly. I now have a device on iOS 13 and can confirm Shadow is working for now. Next update to Shadow will be a full rewrite and will drop iOS 10 and lower support.

**Comment by TheNoim** [comment]
Nice to hear. I know this feeling not having time for any side projects. It is always sad. But I am glad that you will update shadow.
