### ISSUE TITLE
CrackProof Games

### ISSUE THREAD

**Issue by buitim** [jjolano/shadow#3]
Sorry if this is the wrong channel to get in touch with you on, but I just wanted to see if any [CrackProof](https://www.hypertech.co.jp/game/en/) games were on your radar (i.e. Fate/Grand Order, Priconne, (maybe?) DFFOO, (maybe x2?) Revue Starlight, etc.). Apparently, [there was a bypass for F/GO that someone made last year](https://www.reddit.com/r/jailbreak/comments/97ou3x/releasefategrand_order_jailbreak_detection_bypass/), but hasn't been updated in a while. I don't know if you are able to get your hands on their code and somehow rework it, but their bypass does show that it is possible (however definitely not easy). If you're up for a challenge, this is definitely it 😂

EDIT: I could make this into another issue if you'd like (I just don't want to spam you) but I think the latest update to shadow broke Dragalia Lost. I started getting detected without changing any settings.

**Comment by jjolano** [comment]
I can try and take a look to see how they actually implement detection and work around it. I do feel like that bypass breaks on every update due to CrackProof potentially randomizing its class names to prevent tweaks from hooking its functions on every revision? (it also seems the repo is down, so I can't actually check if this is the case)

I did make changes to the path rules in version 2.0.1 which broke a few apps (got a few reports for it). Should be all fine in the latest version now.

**Comment by buitim** [comment]
Much appreciated. But oof that'd be a huge pain in the ass to implement then. That would definitely make sense and give a reason as to why there needed to be an update to the bypass for each update to the client. It also looks like the dev went dark? I wonder if there is someone out there with an archived version of the deb. 

And thanks for the quick fix! For future reference in case something like this happens again, is there a better platform to ping you on or are issues ok?

And of course, keep up the amazing work!

**Comment by Ecric** [comment]
As for the fgo bypass developer, it looks like his repo is up (at least i can see it in cydia)

**Comment by jjolano** [comment]
> Much appreciated. But oof that'd be a huge pain in the ass to implement then. That would definitely make sense and give a reason as to why there needed to be an update to the bypass for each update to the client. It also looks like the dev went dark? I wonder if there is someone out there with an archived version of the deb.
> 
> And thanks for the quick fix! For future reference in case something like this happens again, is there a better platform to ping you on or are issues ok?
> 
> And of course, keep up the amazing work!

GitHub issues are fine. Cydia/Sileo should also give you the option to contact me by email directly (I'll notice these ones faster).

Also, I kinda discovered a very easy way to detect code injection (and then afterwards, root access detection/jailbreak presence) which is not at all bypassable by any means due to the way Substrate/Substitute works 😢  For apps that utilize this method, the best would be to create app-specific patches to remove these checks, but it won't stop developers from implementing the checks directly (which would require actual editing of the binary to bypass).

**Comment by zudas** [comment]
ios12.1(a12) There was an error loading the preference bundle for shadow

~ 2.0.2 ok , 2.0.3 x , 2.0.4 x , 2.0.5 x 

please shadow2.0.2.deb vmfltkd3@gmail.com

**Comment by jjolano** [comment]
Not sure what could be the problem since I haven’t changed anything in compilation settings. Make sure you have the latest Cephei, PreferenceLoader, AppList, and RocketBootstrap packages.

**Comment by zudas** [comment]
good thank jjolano 
Cephei install ^~^

**Comment by jjolano** [comment]
Seems like my repo thing removes Cephei as a dependency.. oops. Will be fixed for the next version.

**Comment by buitim** [comment]
> > Much appreciated. But oof that'd be a huge pain in the ass to implement then. That would definitely make sense and give a reason as to why there needed to be an update to the bypass for each update to the client. It also looks like the dev went dark? I wonder if there is someone out there with an archived version of the deb.
> > And thanks for the quick fix! For future reference in case something like this happens again, is there a better platform to ping you on or are issues ok?
> > And of course, keep up the amazing work!
> 
> GitHub issues are fine. Cydia/Sileo should also give you the option to contact me by email directly (I'll notice these ones faster).
> 
> Also, I kinda discovered a very easy way (and App Store legal too) to detect code injection (and then afterwards, root access detection/jailbreak presence) which is not at all bypassable by any means due to the way Substrate/Substitute works 😢 For apps that utilize this method, the best would be to create app-specific patches to remove these checks, but it won't stop developers from implementing the checks directly (which would require actual editing of the binary to bypass).
> 
> Basically.. detect code injection = jailbroken. If no code injection (to prevent finding jailbreak files), find jailbreak files = jailbroken.

Not sure if this is the correct way of going about it, but you got any tips on how to find the correct methods to hook to prevent detection of code injection? Not too familiar with theos or obj c but I want to see if it's possible to pull off using Flex.

**Comment by jjolano** [comment]
Flex can help find methods, but thats only if they name their methods to clearly show that its for jailbreak detection. Another way is to decrypt the app’s executable (bfdecrypt, CrackerXI) and open it in a disassembler such as Hopper to find any references to detection-related code.

**Comment by buitim** [comment]
> Flex can help find methods, but thats only if they name their methods to clearly show that its for jailbreak detection. Another way is to decrypt the app’s executable (bfdecrypt, CrackerXI) and open it in a disassembler such as Hopper to find any references to detection-related code.

Thanks for pointing me in the right direction! I've always wanted to look into this and this seems like a good place to start. Thanks for the help!

**Comment by huyle0406** [comment]
Hello Jjolano, did you find a way to bybass this? I’m playing Princonne too and it is sad that I cannot play on jailbroken device. On rooted android, I can bybass it by enable suhide and change the pakage name of supersu/, I know that ios and android is different, but I hope you can find a way to bybass this detection. Thanks for your tweak!

Ps: sorry for my bad english.
