### ISSUE TITLE
Naruto X Boruto Nxb ninja Voltage detection

### ISSUE THREAD

**Issue by loru2** [jjolano/shadow#32]
I've been using shadow along with this game for a month, but now they updated jailbreak detection and the game detects jb.
Tried with "Filter Dynamic Linker" but it does not work.
And it works only with Lockdown mode, which disables every tweak... It is a pity, because I play this game with tweaks and mods.
Could it be possible to make it work without Lockdown mode in the future? Thank you

**Comment by bahaafaris** [comment]
I am on iOS 13.3 using the new unc0ver jailbreak.
How did you manage to get into the game?
I downloaded the shadow tweak but even when I activate the shadow lockdown mode it doesn’t work, can you tell what you enabled or disabled? Thank you in advance

**Comment by bahaafaris** [comment]
.

**Comment by loru2** [comment]
Did you install the 2.0.20 from the official repository?
You need to check if it's in the whitelist, because lockdown mode itself is
not enough.
Let me know if I can help you

Il lun 17 feb 2020, 19:36 bahaafaris <notifications@github.com> ha scritto:

**Comment by bahaafaris** [comment]
![D993F66B-A72C-4B0C-88BC-2CEBC3EA2D78](https://user-images.githubusercontent.com/61161579/74712817-e78dec80-522f-11ea-84ea-d48f5865c555.png)
![8469469E-0A1C-4E89-BA53-CF89CAD794BE](https://user-images.githubusercontent.com/61161579/74712824-ec52a080-522f-11ea-800a-93ceae6d083d.png)
![3E44C0C7-F226-420B-99C8-EE47AD4943CC](https://user-images.githubusercontent.com/61161579/74712828-ee1c6400-522f-11ea-81bc-b9311d6dca78.png)

Here take a look, i have installed the latest version of shadow and tried a lot of things but I still get the error 34 violation of something

**Comment by loru2** [comment]
Tap on Applications, check if NxB is selected.
Same for Lockdown Mode

Il mar 18 feb 2020, 08:23 bahaafaris <notifications@github.com> ha scritto:

**Comment by bahaafaris** [comment]
Yes it’s selected

**Comment by loru2** [comment]
Install the last beta version of AppList from Ryan Petrich's beta repo.
It could solve your problem with Shadow and NxB

Il mar 18 feb 2020, 17:51 bahaafaris <notifications@github.com> ha scritto:

**Comment by bahaafaris** [comment]
I am already using the applist from the beta repo, but I think it won’t work because I am on iOS 13.3 and shadow supports only up to 12
Thanks any way

**Comment by loru2** [comment]
I'm using Shadow with iOS 13.2 and it works, so maybe there's a solution
for you


Il mer 19 feb 2020, 08:53 bahaafaris <notifications@github.com> ha scritto:

**Comment by bahaafaris** [comment]
From what repo did you install shadow and the version of shadow and applist.
And did you install anything with it.
Thank you

**Comment by loru2** [comment]
Shadow from its official repo and applist  from Ryan Petrich's beta repo.

>
