### ISSUE TITLE
Could you please look at this bank app?

### ISSUE THREAD

**Issue by sayed001** [jjolano/shadow#4]
Hello jjolano,

This aub bank app is detecting my chimerajb
Please have a look.
AUB M-Bank Bahrain by AHLI UNITED BANK BSC (AUB)
https://itunes.apple.com/us/app/aub-m-bank-bahrain/id771724261?mt=8

Thank you!

**Comment by jjolano** [comment]
This appears to be using KonyLabs’ root detector library. I haven’t fully checked into how the library works, but most likely an app specific or library specific bypass will need to be done for this app.

At the moment, Shadow is focusing on hiding the jailbreak as much as possible with the iOS SDK methods. With some development, maybe the Kony library will be bypassed without any specific code?

**Comment by leehao178** [comment]
Hi @jjolano
https://apps.apple.com/us/app/e4-b8-ad-e5-9c-8b-e4-bf-a1-e8-a8-97-e8-a1-8c-e5-8b/id417698185

this HOME BANK APP had jailbreak detection. the app loading some plugin and always show jailbrakon warning

and I decrypted the ipa and dump headers, i thought i can read some useful files, but its to hard for me, help me pls
https://drive.google.com/file/d/13a7y8qwx7juUguSAtUDUF8oMv6EanAgK/view?usp=sharing

Thank you! :)

**Comment by jjolano** [comment]
Seems like it's using something called Arxan. I'll take a look - hopefully it isn't as advanced as other detection libraries.

**Comment by ShreddedAce** [comment]
Few bank apps:

Bank Norwegian 
https://apps.apple.com/fi/app/bank-norwegian/id1194438643?l=fi

S-Mobiili
https://apps.apple.com/fi/app/s-mobiili/id740514933?l=fi

**Comment by xyy3911** [comment]
@jjolano Hello, how can I contact you? If you have any questions about shadow, what's the reason why restart springboard doesn't work on Apple 10
