### ISSUE TITLE
[Conflict] Newer version of Shadow not works like old one (This is NOT an app request !!)

### ISSUE THREAD

**Issue by CySxL** [jjolano/shadow#43]
https://apps.apple.com/tw/app/%E5%85%A8%E8%81%AF%E7%A6%8F%E5%88%A9%E4%B8%AD%E5%BF%83-%E9%9B%86%E9%BB%9E-%E6%94%AF%E4%BB%98-%E8%B3%BC%E7%89%A9-%E5%8D%B0%E8%8A%B1/id432477263

Same app and same build which worked with Shadow v3.0-1 (Only needs Essential Hooks enabled) before, bypassed successfully.

But with v3.0-2, even I enable Recommended Hooks and Extra Hooks one by one to test, the app cannot be bypassed anymore.

**Comment by jjolano** [comment]
Sorry about that! I didn't realize the quick fix done in v3.0-2 was directly affecting that app. I have just released v3.0-3 which should address this case.

**Comment by CySxL** [comment]
> Sorry about that! I didn't realize the quick fix done in v3.0-2 was directly affecting that app. I have just released v3.0-3 which should address this case.

No worries at all ! I'm just heading to test the v3.0-3 here.

**Comment by CySxL** [comment]
Fixed in v3.0-3 ! Thanks a lot mate !
