### ISSUE TITLE
[Investigation] This is not an app request !!

### ISSUE THREAD

**Issue by CySxL** [jjolano/shadow#44]
**I'm totally ok with using old builds !! Providing these info in order to hope that the differences between IPAs can help for investigation of some new detections !**
-----------------

https://apps.apple.com/tw/app/%E5%85%A8%E8%81%AF%E7%A6%8F%E5%88%A9%E4%B8%AD%E5%BF%83-%E9%9B%86%E9%BB%9E-%E6%94%AF%E4%BB%98-%E8%B3%BC%E7%89%A9-%E5%8D%B0%E8%8A%B1/id432477263

^The above app in build 3.0.24 can be bypassed with only Essential Hooks enabled. 

But with build 3.0.25 and 3.0.26(latest), app crashes immediately even with Recommended Hooks and Extra Hooks.

(Currently using 3.0.24 and 3DAppVersionSpoofer tweak to make the app think that it's on 3.0.26 to prevent the update pop-up.）

----------------

https://apps.apple.com/tw/app/%E5%85%A8%E6%B0%91%E5%81%A5%E4%BF%9D%E8%A1%8C%E5%8B%95%E5%BF%AB%E6%98%93%E9%80%9A-%E5%81%A5%E5%BA%B7%E5%AD%98%E6%91%BA/id578186283

^The above app in build 5.15.6 can be bypassed with only Essential Hooks enabled. 

But with builds above 5.16.0+, app crashes immediately even with Recommended Hooks and Extra Hooks.

(Currently using 5.15.6 and 3DAppVersionSpoofer tweak to make the app think that it's on 5.16.12 to prevent the force update pop-up.）

----------------
Add them here because maybe you have interest to compare the changes of IPAs and have some findouts to help more people. 

Btw they are both in Taiwan Appstore.

**Comment by jjolano** [comment]
For the first app, I am able to bypass the latest version on my device. Looks like they added some hooking checks which should be handled by Loaded Modules hook (was updated in 3.1).

Second app will need work

**Comment by CySxL** [comment]
> For the first app, I am able to bypass the latest version on my device. Looks like they added some hooking checks which should be handled by Loaded Modules hook (was updated in 3.1).
> 
> The app on 3.0.26 always crashes for me even if I don't enable any toggles 😂. What toggles do you enable ? Or I guess it's just substitute time again.
> 
> Second app will need work
  Take your time !! No rush at all.

**Comment by jjolano** [comment]
Will close this for now as it is likely detection that Shadow doesn't handle yet. Continue using old versions, and maybe in the future these apps could work.
