### ISSUE TITLE
Crash log for app « paiement mobile »

### ISSUE THREAD

**Issue by LileAuTresor** [jjolano/shadow#47]
I know you have other things to do and lot of people ask you the same thing but if you can check why I can’t bybass jailbreak detection on this app you will save my life !
https://apps.apple.com/fr/app/paiement-mobile-ca/id1038067309
The app doesn’t crash but still detect there is a « technical problem, for security reason, these app can’t be used on that phone ». I tested all know tweak, none work (shadow v3.0-0.rc5, a-bypass, liberty lite, flyJB X, Hestia, vnodebypass, ...) . I'm on unc0ver ios 13.5.

Screenshot : https://imgur.com/a/TRlDvlh
Crash log : https://pastebin.com/8DEBAxJR

Thanks if you have time to check !

**Comment by jjolano** [comment]
Thanks for the crash log. It suggests it's to do with the "Runtime Class Lookups" option which may not be playing nicely on unc0ver (I'm using Taurine).

Luckily, the current version (v3.0-5, not rc5) seems to be able to get past that message regardless.

**Comment by LileAuTresor** [comment]
Yes, I confirm that without "Runtime Class Lookups" checked it doesn’t crash but the bypass detection doesn’t work.
I have tested with 3.0-5-3+debug and not 3.0 rc5... any suggestion?

**Comment by jjolano** [comment]
Would you be able to give the the output of the command: `dpkg -S /usr/lib/substitute-inserter.dylib`

**Comment by LileAuTresor** [comment]
iPhone-de-M:~ mobile$ dpkg -S /usr/lib/substitute-inserter.dylib                              
science.xnu.substituted: /usr/lib/substitute-inserter.dylib                                        
iPhone-de-M:~ mobile$

**Comment by jjolano** [comment]
At this point I have a feeling it's related to Substitute/Substrate since that's pretty much the main difference between our jailbreak setups. libhooker (Taurine) hooks functions differently, which my own jailbreak detection app doesn't detect.

If you want to test, you will probably get Runtime Modifications detected with latest version of Shadow: https://github.com/jjolano/EffulgenceDemo/releases/tag/v1.0

This may take a while to figure out.

**Comment by LileAuTresor** [comment]
Artifacts detected :
- writable root filesystem
- Shell present
- Code injection platform

All is checked on shadow except « device masquerade » because I’m on 13.5. 
The app crashed first but not the second time with « runtime class lookups » checked.

**Comment by LileAuTresor** [comment]
I have test your ipa with A-bypass, it’s detect :
- Runtime modification
- Code injection
- Shadow

So... no « runtime modification » detected with shadow but still some detections...

**Comment by jjolano** [comment]
Interesting that it detected shell...

Can you do the commands:
`ls /bin`
`ls /usr/lib`
`dpkg -S /bin/bash`
`dpkg -S /bin/sh`
`dpkg -S /bin/zsh`

**Comment by LileAuTresor** [comment]
iPhone-de-M~ mobile$ dpkg -S /bin/bash     
bash: /bin/bash                                  
iPhone-de-M:~ mobile$ dpkg -S /bin/sh       
local diversion from: /bin/sh                    
local diversion to: /bin/sh.distrib              
bash: /bin/sh                                    
iPhone-de-M:~ mobile$ dpkg -S /bin/zsh      
dpkg-query: no path found matching pattern /bin/zsh

**Comment by LileAuTresor** [comment]
I don't know if it matters but I have substitute 0.1.15 installed, newer versions make crash some of my tweaks. Let me know if you want me to try with another version of substitute.

**Comment by jjolano** [comment]
[me.jjolano.shadow_3.0-5-13+debug_iphoneos-arm.zip](https://github.com/jjolano/shadow/files/10025996/me.jjolano.shadow_3.0-5-13%2Bdebug_iphoneos-arm.zip)
Try this build and see if it makes any difference on Effulgence and your app.
If still no different, try with latest Substitute.

**Comment by LileAuTresor** [comment]
No change on substitute 0.1.15. 
With updated substitute on Effulgence :
- shell present
- Runtime modification
- Code injection platform
- Shadow
I was obliged to disabled runtime class lookups because of crash. 

On my app, it’s work with only recommandés hooks checked !!!!! Thank you very much !

let me know if you want some crash logs with this try. 

Have a good day

**Comment by LileAuTresor** [comment]
I tested shadow on all my apps where A-Bypass was working.
Everything seems OK except for 3 applications:
- CA-ELS (https://apps.apple.com/fr/app/ca-els/id1323967758): jailbreak detection popup but I can still use the application
- Doctolib (https://apps.apple.com/fr/app/doctolib/id925339063): detection of jailbreak, unusable application
- Paypal (https://apps.apple.com/fr/app/paypal/id283646709): application crash, unusable.

If you want to continue the investigation with me, I can provide you with the information you need. Tell me if you want to check and if you want me to open a issue for each application.

**Comment by jjolano** [comment]
All 3 apps seem to be working for me. Aside from PayPal, I can confirm jailbreak detection when I disable the bypass. I do feel it points to your version of substitute, especially if Shell and Code Injection Platform are being detected on Effulgence. Those checks are very basic, and it suggests some of the File System hooks (this is an essential hook) are not working correctly or at all. Shadow includes some hard-coded checks for these detections specifically.

**Comment by LileAuTresor** [comment]
OK I understand. If I can help you to test stuff don’t hesitate, it’s with pleasure.

**Comment by jjolano** [comment]
@LileAuTresor Can you check if version 3.3 has improved this issue?

**Comment by LileAuTresor** [comment]
I confirm that the 3 apps work with the 3.3 update. 

On the other hand there is always a crash with "runtime class lookups" and the Effulgence app always detects "runtime modifications" and "shadow" with all the hooks checked (except runtime class lookups). 

Let me know if you need crash logs or something else. 

If I may remark, the apps seem slower than with the A-bypass tweak activated... Anyway, very good job!
