### ISSUE TITLE
Animal Crossing Pocket Camp detection

### ISSUE THREAD

**Issue by Smethan** [jjolano/shadow#5]
Is it possible to bypass Animal Crossing: Pocket Camp’s jailbreak detection? There’s no current bypass, so is there any progress on that front? This may not be the place to ask, but if there’s any progress or any type of lead, I’d like to have a crack at it.

**Comment by jjolano** [comment]
If it is possible to obtain a decrypted executable of the app, I can take a look in a disassembler and check the methods of detection. Unfortunately, it seems that it crashes on launch, and the only way (that I know of) to obtain a decrypted executable is to have it actually running on the device for bfdecrypt/CrackerXI to decrypt the app.

**Comment by Smethan** [comment]
I have a decrypted executable, should I upload it here?

**Comment by jjolano** [comment]
Sure. I can take a look at it

**Comment by Smethan** [comment]
Here's a download link
https://mega.nz/#!jTBRTQiB!lkMyIz9Uvj9-1dcJLO_nSiJLBrfpHqrntnu6ACrBa9U

**Comment by Smethan** [comment]
I did find a reference to a "rooted_jailbroken" variable at offset 0000000100C5AF70, which seems to be inside something called "UnityEngine::Analytics::DeviceInfoEvent". I don't know if this helps, nor do I exactly know how to use it in a tweak, but I thought I may as well share what I found

**Comment by jjolano** [comment]
Definitely something for me to further look into, if the Unity Engine (or a plugin) is providing jailbreak detection functionality. Maybe I can look up some developer documentation on that...

**Comment by Smethan** [comment]
According to the documentation [here](https://docs.unity3d.com/ScriptReference/Analytics.Analytics.html) it seems to be a CustomEvent that Nintendo wrote, as that method doesn’t seem to be mentioned in any of the documentation.

**Comment by Smethan** [comment]
After looking into it some more, it doesn’t seem like we can hook the method for the DeviceInfoEvent as it’s compiled with il2cpp, and it seems there’s no way of hooking c# methods in theos. The only way I can think of now is finding what it checks for and hiding that.
