### ISSUE TITLE
Cr4shed log for K-Plus App

### ISSUE THREAD

**Issue by kn3w** [jjolano/shadow#50]
https://pastebin.com/NmufaGFP

**Comment by jjolano** [comment]
Thanks for the log. This will take a while to figure out as it seems substitute-specific. I wish I had a device on unc0ver...

For now, please downgrade to version 2.

**Comment by jjolano** [comment]
Please check if version 3.3 has solved this crash.

**Comment by kn3w** [comment]
> 

Still crashing 
(All Essential+Recommend hooks enabled)
https://pastebin.com/Tm1FP6b7

**Comment by jjolano** [comment]
See if 3.3.3 has fixed this crash

**Comment by kn3w** [comment]
> See if 3.3.3 has fixed this crash

👍🏻 3.3.3 fixed the crashes on the app version 5.15.0  

On a newer version of app are still detected a jailbreak (5.15.0 or later.)

but its okay, just downgraded the app to 5.15.0 and its working fine. 

Thank you so much.

**Comment by jjolano** [comment]
It seems like they added Substitute-specific detection in the newer versions since i am able to bypass with libhooker
