### ISSUE TITLE
dpkg error with 3.1.2

### ISSUE THREAD

**Issue by CySxL** [jjolano/shadow#51]
With Shadow 3.1.2 installed. Installing/removing Crane afterwards would have the below logs : ![image](https://user-images.githubusercontent.com/15531137/203007824-39f39d0b-2cf5-43fe-bb4b-b73ce07025ae.jpeg)

Without Shadow 3.1.2 installed, installing/removing Crane got logs below : ![image](https://user-images.githubusercontent.com/15531137/203007357-475e42b7-0882-4681-80b8-cdfea77f3c74.png)

Differences : ![image](https://user-images.githubusercontent.com/15531137/203008685-a70e985b-9925-4718-b56b-1f2d0fee9f3e.jpeg)

**Comment by jjolano** [comment]
Not related to Shadow, as it only operates on sandboxed applications. It looks like an issue with your cydia package.

**Comment by CySxL** [comment]
> Not related to Shadow, as it only operates on sandboxed applications. It looks like an issue with your cydia package.

Weird... Cuz it happens only with Shadow installed.

**Comment by jjolano** [comment]
It looks like the selector from the error message is within SpringBoard, more specifically the 3D Touch/Force Touch menu on app icons and I don't hook anything related to that. I believe Crane itself does though.

**Comment by jjolano** [comment]
Does this happen with any previous versions of Shadow?

**Comment by CySxL** [comment]
> Does this happen with any previous versions of Shadow?

Just tested. Not happens on Shadow 1.3.1. Only happens on 1.3.2.

**Comment by jjolano** [comment]
Do you use the "Always-On" option in Shadow?

**Comment by CySxL** [comment]
> Does this happen with any previous versions of Shadow?

Do you mind we discuss on Discord or something ? Git's notifications are very not in time 😂

**Comment by jjolano** [comment]
> > Does this happen with any previous versions of Shadow?
> 
> Do you mind we discuss on Discord or something ? Git's notifications are very not in time 😂

For this issue specifically sure, what is your tag?

**Comment by CySxL** [comment]
> Do you use the "Always-On" option in Shadow? See if it still happens with everything disabled.

Nah I never use that. Only using specific app settings.

**Comment by CySxL** [comment]
> > > Does this happen with any previous versions of Shadow?
> 
> > 
> 
> > Do you mind we discuss on Discord or something ? Git's notifications are very not in time 😂
> 
> 
> 
> For this issue specifically sure, what is your tag?

CydaiDEV#4450
