### ISSUE TITLE
Everything crashes 

### ISSUE THREAD

**Issue by dhd111** [jjolano/shadow#52]
After I update shadow I have random crashes 
[cr4shed-log.zip](https://github.com/jjolano/shadow/files/10059922/cr4shed-log.zip)

**Comment by jjolano** [comment]
Thanks for the logs. I hate substitute

Will push a fix soon

**Comment by jjolano** [comment]
Please try v3.1.3-1

**Comment by TimeDiver0** [comment]
Speaking as someone who got the same crashes as dhd111 (at least, the _exact_ **same** ones for springboardd), v3.1.3-1 **_seems_** to have fixed those crashes (which occurred as frequently as several per minute).

I'd planned on submitting my own bug report after downgrading from v3.1.2 (the newest release, in the dead of night) to v3.0-6 (which didn't result in the frequent springboardd crashes).

**Comment by jjolano** [comment]
Thanks for confirming, will close for now

**Comment by dhd111** [comment]
I forgot to add something : random respring 
And the device enter into loop respring even after reboot and ReJailbreak
