### ISSUE TITLE
Outlook app crashing

### ISSUE THREAD

**Issue by ibrahimqatar** [jjolano/shadow#56]
Hi,

I think this is one of the best jailbreak detection bypasses so far!

it works on the latest teams for my corporate account (no jailbreak detection bypass worked).

but the problem is with Outlook, it bypasses all the checks just fine but it crashes a few seconds after the app is launched, see the crashlog generated by Cr4shed:

https://pastebin.com/K6uwm4eZ

I use version 4.2234.2 of Outlook because this is the latest I can use on iOS14.

I hope this is fixable.

**Comment by jjolano** [comment]
Thanks, I will look into this as I also experience random crashes on Outlook.

**Comment by ibrahimqatar** [comment]
> Thanks, I will look into this as I also experience random crashes on Outlook.

Superb! Let me know if you want me to test anything.

**Comment by jjolano** [comment]
Please try version 3.3 and see if there's any improvement. Some hooking code was changed which may help.

**Comment by ibrahimqatar** [comment]
Still crashes, I tried the minimum options to bypass the detection and I still have the same problem: 

https://pastebin.com/dMtCML7H

**Comment by ibrahimqatar** [comment]
I tried 3.3.3 and it’s still crashing, did you attempt to fix this crash with your updates? I tried every update you pushed with the sane result.

thank you very much for your effort!

**Comment by jjolano** [comment]
Still looking into this one. Its a very tricky one so far. Wish cr4shed would give a full log and not just the crashed thread

**Comment by kbeeveer46** [comment]
@ibrahimqatar How did you get it to work for Outlook? I just started getting messages from Outlook today that it's being blocked from opening because I have a jailbroken device. I enabled the Always-on setting and every setting in the Bypass settings screen. I'm also getting blocked from using Microsoft Teams. Both Outlook and Teams started showing the same "Device Non-Compliant" error message today.

**Comment by jjolano** [comment]
I managed to fix the crashing on my end with version 3.3.5. Please check if it also fixed it on your end.

**Comment by kbeeveer46** [comment]
What settings do you recommend be enabled for Microsoft apps like Outlook and Teams? I've tried enabling them all but I get the same error message for both apps...

> This app cannot be used because you are using a jailbroken device. Contact your IT administrator for help.

**Comment by ibrahimqatar** [comment]
> 

Still crashing here, I have all settings enabled but Device Masquerade and I only have low-level file handles enabled from extra hooks.

what settings do you have?

**Comment by jjolano** [comment]
I run all options enabled. Might have to see another cr4shed log if you have it

**Comment by ibrahimqatar** [comment]
> I run all options enabled. Might have to see another cr4shed log if you have it

This is a crashlog with all settings enabled:

https://pastebin.com/JNNCyvRB

**Comment by jjolano** [comment]
Seems identical to the original log 😢 

I wonder if it's to do with a particular option? Would you be able to test each option individually and see which one(s) are causing a crash? That should narrow it down further for me.

**Comment by ibrahimqatar** [comment]
> Still crashing here, I have all settings enabled but Device Masquerade and I only have low-level file handles enabled from extra hooks.
> 
> what settings do you have?

As I mentioned here, I had these options on only.

As for the crashlog, I used what you had to at least find what’s different.

**Comment by jjolano** [comment]
> As for the crashlog, I used what you had to at least find what’s different.

I meant that the crash log shows the same reason for the crash as the original log. It doesn't change if you have all options enabled if one of them is causing it. What I'm after is what is the particular option causing the crash, and that way it narrows it down

**Comment by jjolano** [comment]
So we have 4 options under essential, 4 under recommended, and 1 from extra. Are you saying that this specific configuration is the tipping point between crashing and not crashing?

**Comment by jjolano** [comment]
Thanks, I'll have a closer look at that option and see what I can do.

**Comment by jjolano** [comment]
3.3.6 makes some changes to the hooks in question, and I also discovered another hook in Runtime Class Lookups causing crashes which I fixed up as well. Hopefully this works out

**Comment by ibrahimqatar** [comment]
> 3.3.6 makes some changes to the hooks in question, and I also discovered another hook in Runtime Class Lookups causing crashes which I fixed up as well. Hopefully this works out

Still causing a crash, the only option which causes the crash (and the one which bypasses the jailbreak detection) is low-level file handles option.

**Comment by jjolano** [comment]
😭 

I'll keep taking a look at it, but in its current state there's not much more I can change about those particular hooks aside from a rewrite of some of the restriction logic. My own Outlook is working and I also use Taurine, so it will take some time to figure this out

**Comment by ibrahimqatar** [comment]
> 😭 
> 
> 
> 
> I'll keep taking a look at it, but in its current state there's not much more I can change about those particular hooks aside from a rewrite of some of the restriction logic (which is basically the core of Shadow). My own Outlook is working and I also use Taurine, so it will take some time to figure this out

The thing is, different corporations have different levels of protection as far as I have tested. For example my wife's company applies the same level as mine, but my sister's company have their protection set very high not even shadow can bypass the detection popup. This applies to teams as well.

So I think that's why yours work ok.

**Comment by ibrahimqatar** [comment]
Just tested outlook on Taurine 14.3 on my old device and it seems to be working fine now without crashing, I will be closing this issue.
