### ISSUE TITLE
Last few versions cause freezes and 3.0-6 is good

### ISSUE THREAD

**Issue by sahinkaa** [jjolano/shadow#58]
Hi there. I’m on iOS 12.4 uncover.
Last versions are terribly freezing my phone. The keyboard comes like 3-4 seconds after I write something, in Whatsapp messages. I had to go back to 3.0-6 and it is working normal now. I don’t know what did you change after that but it is not good. I can test deb files for you if you want to fix this.

**Comment by jjolano** [comment]
Please check if version 3.3 has improved this.

**Comment by NeHyci** [comment]
I ran into the same problem when I enabled Loaded Modules and Mach Service Lookups at the same time on version 3.3

**Comment by jjolano** [comment]
> I ran into the same problem when I enabled Loaded Modules and Mach Service Lookups at the same time on version 3.3

Does it happen without Mach Service Lookups?

**Comment by NeHyci** [comment]
> > I ran into the same problem when I enabled Loaded Modules and Mach Service Lookups at the same time on version 3.3
> 
> 
> 
> Does it happen without Mach Service Lookups?

No.
Apps with bypassing enabled cannot be started (the startup interface is always displayed).This only happens when both Loaded Modules and Mach Service Lookups are enabled

**Comment by sahinkaa** [comment]
> Please check if version 3.3 has improved this.

well it seems to be fixed. thank you. i don't understand all those bypass settings, but keeping it default, i haven't changed anything, though none of my apps came with a jb warning so far. thank you.

**Comment by NeHyci** [comment]
> I ran into the same problem when I enabled Loaded Modules and Mach Service Lookups at the same time on version 3.3

Hmmm... I made a mistake. The problem I encountered was different from this issue.

**Comment by jjolano** [comment]
Seems original issue is fixed. Will close this for now
