### ISSUE TITLE
Not a current issue. but I have to report.

### ISSUE THREAD

**Issue by sahinkaa** [jjolano/shadow#59]
I just found out that v2 was causing the icons on the Springboard not able to rearrange. I had to disable all of the tweaks and rearrange the icons back then, for the last 2 years hahaha... Even in Safe mode it wasn't working. What a waste of time it was. So v3 fixed it too.

**Comment by jjolano** [comment]
At least it's working!

**Comment by sahinkaa** [comment]
Yeah. 3.3 feels perfect.
