### ISSUE TITLE
Error loading preference bundle !

### ISSUE THREAD

**Issue by xjay111** [jjolano/shadow#6]
Iphone 6 and IOS 11.1 . 
I got this error when open shadow setting page and i have no idea what is wrong .
Help!

**Comment by jjolano** [comment]
Please ensure you have the latest Cephei, PreferenceLoader, and RocketBootstrap installed.

Sources:
https://repo.chariz.io (Cephei)
http://rpetri.ch/repo (PreferenceLoader, RocketBootstrap)

**Comment by xjay111** [comment]
Thanks . Working fine right now !
