### ISSUE TITLE
Version differences

### ISSUE THREAD

**Issue by CySxL** [jjolano/shadow#61]
There is an app can be bypassed with 3.3-beta2 and beta3 and all previous builds, but not with the current released repo version 3.3.

App : https://apps.apple.com/tw/app/line-pay-%E6%94%AF%E4%BB%98%E9%AB%94%E9%A9%97-%E7%85%A5%E7%84%B6%E4%B8%80%E6%96%B0/id1563230455  

What it needs :
![image](https://user-images.githubusercontent.com/15531137/203986967-74f0a56a-67f4-4cff-8d0d-5780cd3043f6.png)
![image](https://user-images.githubusercontent.com/15531137/203986979-0cd02f4e-0fd7-4a7d-b548-81bc0394ecdb.png)

**Comment by nk950357** [comment]
我的3.3可以
shadow 3.3加入了一個enable shadow service開關
![image](https://user-images.githubusercontent.com/51433626/203997430-21a09266-03f1-4683-9fbd-99f4cbe56934.png)
我一開始裝完也是發現不能用 開了那個開關就可以了 你試試看
![image](https://user-images.githubusercontent.com/51433626/203997584-0dc499f1-f751-4efe-9c6a-432abb766a77.png)

**Comment by CySxL** [comment]
> 我的3.3可以
> 
> shadow 3.3加入了一個enable shadow service開關
> 
> ![image](https://user-images.githubusercontent.com/51433626/203997430-21a09266-03f1-4683-9fbd-99f4cbe56934.png)
> 
> 我一開始裝完也是發現不能用 開了那個開關就可以了 你試試看
> 
> ![image](https://user-images.githubusercontent.com/51433626/203997584-0dc499f1-f751-4efe-9c6a-432abb766a77.png)
> 
> 

感謝！我自己也可以使用，是幫群友回報的。尷尬惹原來其實沒問題哈哈哈

btw 是chenchen嗎？

**Comment by nk950357** [comment]
> > 我的3.3可以
> > shadow 3.3加入了一個enable shadow service開關
> > ![image](https://user-images.githubusercontent.com/51433626/203997430-21a09266-03f1-4683-9fbd-99f4cbe56934.png)
> > 我一開始裝完也是發現不能用 開了那個開關就可以了 你試試看
> > ![image](https://user-images.githubusercontent.com/51433626/203997584-0dc499f1-f751-4efe-9c6a-432abb766a77.png)
> 
> 感謝！我自己也可以使用，是幫群友回報的。尷尬惹原來其實沒問題哈哈哈
> 
> btw 是chenchen嗎？

沒錯ww

**Comment by CySxL** [comment]
Closed as false report. :/
