### ISSUE TITLE
Not working (v3.3.5)

### ISSUE THREAD

**Issue by SethWiiPlaza** [jjolano/shadow#65]
Frequent app crashes 

iPhone 11
System Version: i0S 14.0.1
uncOver jailbreak Version: 8.0.2

**Comment by jjolano** [comment]
I really don't know what to look for here.

- Are you sure it's not a tweak conflict?
- Are the crashing apps a result of jailbreak detection? I don't guarantee it working for *all* apps.
- If the app doesn't have jailbreak detection, what app is crashing and what settings do you have?
