### ISSUE TITLE
Shadow settings do not appear in Settings app after installation

### ISSUE THREAD

**Issue by aegis-dev** [jjolano/shadow#66]
Shadow settings do not appear in Settings app after installation. Unc0ver 8.0.2, iOS 13.3.1

**Comment by aegis-dev** [comment]
I do have PreferenceLoader 3.0.3 installed. I am sure that closing the Settings app doesn't work. Am I understanding correctly that Shadow configuration should appear in Settings main view at the bottom where all other apps are listed?

**Comment by aegis-dev** [comment]
Any other way to enable Shadow with the default configuration without the Settings app? CLI interface?

**Comment by jjolano** [comment]
> I do have PreferenceLoader 3.0.3 installed. I am sure that closing the Settings app doesn't work. Am I understanding correctly that Shadow configuration should appear in Settings main view at the bottom where all other apps are listed?

Yes, it should appear in the same section with any other tweaks that you have installed. If anything, try a full uninstall of the tweak and reinstall. Or you can try `preferred` which is a replacement for `preferenceloader`


> Any other way to enable Shadow with the default configuration without the Settings app? CLI interface?

No other way. But this is a good idea.

You can try to manually create the preferences file here: `/var/mobile/Library/Preferences/me.jjolano.shadow.plist` with the key `Global_Enabled` set to `true`. I suggest copying another plist in the same folder and editing it.

**Comment by aegis-dev** [comment]
Adding `https://creaturecoding.com/repo/` Cydia repo and installing `preferred` worked! Thank you very much! 😎
