### ISSUE TITLE
iOS 15 support with Xina

### ISSUE THREAD

**Issue by ibrahimqatar** [jjolano/shadow#68]
It doesn’t seem to have any effect on Xina with iOS15 on iPhone 13.

I’ll be glad to help you test things out if you don’t have a device that works with Xina.

**Comment by jjolano** [comment]
Thanks. Theoretically should be able to get it working with minimal changes.
- Probably most important: Do settings work/do they retain changes? Its possible that apps are unable to access outside sandbox for settings as this currently depends on libSandy working.

**Comment by jjolano** [comment]
Also it would be helpful to know the directory structure for `/var/jb`. Output of command `find /var/jb/.` would be useful

**Comment by ibrahimqatar** [comment]
I’ve been seeing reports that the newest version is working on Xina, it doesn’t actually, I tried it on both 15.0.2 and 15.1.1 on iPhone 13 Pro Max.

For example I can bypass teams jailbreak detection applied from my company using the same Shadow version on 14.3 Taurine but I can’t do the same on Xina (both teams are on the same version).

**Comment by jjolano** [comment]
Thanks for the information. Looks like there's a small change I can make for Xina.

Are there any other apps where it works/used to work? I'm not sure what tweak injection platform Xina is using (substitute or libhooker) but that could make a difference.

**Comment by ibrahimqatar** [comment]
> Thanks for the information. Looks like there's a small change I can make for Xina.
> 
> 
> 
> Are there any other apps where it works/used to work? I'm not sure what tweak injection platform Xina is using (substitute or libhooker) but that could make a difference.
> 
> 

The dev claims he's using both but looking at the files, it's most probably only substitute.

**Comment by ibrahimqatar** [comment]
Teams is still detectable with Shadow 3.4 with all options on on Xina

**Comment by jjolano** [comment]
If you want a clear cut example of what I mean (Substitute vs libhooker) try this out: https://github.com/jjolano/EffulgenceDemo/releases/tag/v1.0
