### ISSUE TITLE
Another banking app

### ISSUE THREAD

**Issue by Crazor** [jjolano/shadow#7]
Here‘s another (german) banking app:

https://apps.apple.com/de/app/eb-banking/id1354902548

Support for this one could probably also affect a bunch of other (popular) German banks and their tools (SecureCode etc), as they are all by the same developer

**Comment by gruutak** [comment]
I'm also having an issue with another banking app (this one is brazilian): https://apps.apple.com/br/app/c6-bank/id1463463143?l=en

Maybe it could be the same problem.
