### ISSUE TITLE
eWallet Crash

### ISSUE THREAD

**Issue by budakcivic** [jjolano/shadow#70]
Hi bro, firstly thanks a lot for updating the shadow. I did installed shadow on latest XinaA15 jailbreak and no issues for all of banking and eWallet app except 1 TouchNGo eWallet. This app still detect jailbreak until recommended hooks while if enable extra hooks the app forcing close. 

At the moment cant provide crashed log as Im not sure the tweak compatible with ios15 or not. 

Link to the apps : https://apps.apple.com/my/app/touch-n-go-ewallet/id1344696702

This app can be bypassed by tweak A-Bypass on ios 14.

**Comment by jjolano** [comment]
If there is something that works already, I suggest using that. I do not take any app requests.
