### ISSUE TITLE
[Tough Detection Banking Apps] Us app store links provided

### ISSUE THREAD

**Issue by imraan1992hk** [jjolano/shadow#71]
Here are some apps that are hard to bypass.

Za Bank: https://apps.apple.com/us/app/za-bank/id1477150600?l=en

Octopus HK: https://apps.apple.com/us/app/octopus-%E5%85%AB%E9%81%94%E9%80%9A/id1114430602

Hang Seng Bank: https://apps.apple.com/us/app/hang-seng-personal-banking/id1039256353?l=en (Currently only using an older version, 5.0, works with liberty lite. Newer versions crash with or without any bypass)

Payme: https://apps.apple.com/us/app/payme-from-hsbc/id1184264977 (currently works with liberty lite or A-bypass, Shadow 3.3.7 not able to bypass at all)

These are some of the hardest/impossible apps to bypass. I'd be willing to donate if you can look into these and bypass them.

**Comment by jjolano** [comment]
Sorry, I don't think I'll be looking at these. They likely need something app-specific right now, and Shadow isn't designed for that.
