### ISSUE TITLE
TMB Bank force close

### ISSUE THREAD

**Issue by SATIS8CHIMPALEE** [jjolano/shadow#73]
force close when Enforce Sandbox or Hide Executable Memory is enable 

after disable 2 options above still cannot bypass, no crashing log about this app

https://apps.apple.com/th/app/ttb-touch/id884079963

palera1n, ios15.1, iPhone x

**Comment by jjolano** [comment]
You will likely need something app specific. Shadow is not designed for that.

I will add in a disclaimer for extra hooks as they can cause crashes
