### ISSUE TITLE
Longer time to userspace reboot

### ISSUE THREAD

**Issue by CySxL** [jjolano/shadow#74]
I noticed that with some previous very old builds (3.1.x iirc) and 3.4 (latest currently), userspace reboot and re-jailbreak take more longer time to process. Like the white Apple logo booting screen will take 2-3 times flashing.

Edit : 
tested with Shadow 3.4 disabled and Shadow 3.3.7 enabled, the process time : 15 seconds at most.

Shadow 3.4 enabled process time : 3 minutes at least.

iOS : 14.8
Jailbreak tool : unc0ver 8.0.2
Model : iPhone 11 Pro Max

**Comment by keldey** [comment]
Tested Shadow 3.4 on iPhone 11 unc0ver with Shadow Service and Global Settings Always-On, no issue of increased userspace reboot speed.

**Comment by jjolano** [comment]
Think I found the issue. Should be better next update.

**Comment by CySxL** [comment]
> Think I found the issue. Should be better next update.

Thanks a lot !! I should recall that the culprit of old builds was also regression. 😂😂

**Comment by CySxL** [comment]
> Think I found the issue. Should be better next update.

Confirmed fixed !! Thanks a lot as always !!

**Comment by CySxL** [comment]
> Tested Shadow 3.4 on iPhone 11 unc0ver with Shadow Service and Global Settings Always-On, no issue of increased userspace reboot speed.

seems your test is not correct tho.
