### ISSUE TITLE
Add jailbreak detection bypass tiktok

### ISSUE THREAD

**Issue by mino389** [jjolano/shadow#75]
https://github.com/haoict/tiktok-god/blob/master/JailbreakBypass.xm

**Comment by jjolano** [comment]
Why not just use that if that's already a tweak?

**Comment by robertybob** [comment]
> Why not just use that if that's already a tweak?

Tbf to OP the tweak hasn’t been updated since early 2022 so doesn’t work with latest version of Tiktok, however the dev is still active so hopefully they update the tweak soon :)
