### ISSUE TITLE
Cannot move icons

### ISSUE THREAD

**Issue by sahinkaa** [jjolano/shadow#77]
Hi. What could be causing this? During the last 2 years, when there was Shadow 2.x I couldn't move Sproigboard icons without disabling ALL of the tweaks. After Shadow 3.0x somehow it got fixed. Now there's this problem: when I uninstall Shadow 3.x, I cannot move the icons again. When I install it back, I can move the icons. Strange behavior. How could it be possible? How can Shadow 3 enable it and how can it cause this disfunction when I uninstall it? I don't want to have it installed, because even though I don't enable it, it causes my keyboard to freeze as we discussed a couple of weeks ago. Turns out I don't need Shadow for any of my apps, but how can I fix the icons not moving issue when I uninstall Shadow?

**Comment by sahinkaa** [comment]
There is a workaround for this; "Try using Choicy to disable injection into the druid daemon"
I did this and it worked. So is Shadow doing the same thing now?

**Comment by jjolano** [comment]
Shadow really shouldn't be causing this at all (nor fixing it for that matter). The only things it actually operates in are UI apps like SpringBoard and any enabled apps, not daemons. The SpringBoard code only initializes Shadow Service running in the background and regenerates the jailbreak file database. It doesn't touch any user interface elements.

**Comment by jjolano** [comment]
I checked the `druid` daemon on my own device and Shadow doesn't even load into it.

**Comment by jjolano** [comment]
@sahinkaa Regarding keyboard freezes, do you have the tweak Saw? I just installed it to try and noticed my keyboard being slow.
