### ISSUE TITLE
Saw conflict

### ISSUE THREAD

**Issue by ibrahimqatar** [jjolano/shadow#79]
Any reason why there is a conflict with Saw in the newest Beta version?

**Comment by jjolano** [comment]
Causes some severe keyboard lag for Shadow-enabled apps on my device, can't really determine the cause. Unless it's just one particular option of Saw causing it (possibly removing the bottom spacing).

**Comment by jjolano** [comment]
I'll remove the conflict for now, but users of this tweak should be wary of the potential issues
