### ISSUE TITLE
Crashes on Xina 1.1.5 on iOS 15.1.1 in the new beta 3.5

### ISSUE THREAD

**Issue by ibrahimqatar** [jjolano/shadow#80]
Apps crash when I have shadow enabled for them and some do load but with severe delay in launch time

**Comment by jjolano** [comment]
This is likely from Xina's implementation of libhooker, as the current beta is testing my HookKit Framework (which prefers libhooker if available on the system).

**Comment by jjolano** [comment]
Latest beta now has toggles to change the hooking library used. Default behaviour is to use Substrate-compatible methods, as it is for the stable 3.4.1. See if this still has issues with Xina.

**Comment by ibrahimqatar** [comment]
I'm having HIK-Connect as an example here, Fishhook seems to be the fastest, it loads in a second while the rest takes from 4-5 seconds (on an iPhone 13 Pro Max)

**Comment by jjolano** [comment]
Any crashes? Fishhook is not as powerful as the real deal hooking libraries.

**Comment by ibrahimqatar** [comment]
> Any crashes? Fishhook is not as powerful as the real deal hooking libraries. (but if it works, it works. Benefit is evading substrate/substitute specific detection)

It crashes for certain apps as well with any of the settings, didn't experience this with the older version. Also. With 3.4.1, I can bypass jailbreak detection for some apps which only crashes on the beta version with all options being enabled. The beta definitely doesn't play well with Xina

**Comment by jjolano** [comment]
Can you provide the crash log from Settings? Ill see what can be done about the crashes

**Comment by ibrahimqatar** [comment]
> Can you provide the crash log from Settings? Ill see what can be done about the crashes

https://pastebin.com/ZM0a92Ds

This is from this game:

https://apps.apple.com/us/app/superstar-smtown/id890937532

3.4.1 only couldn't bypass the jailbreak detection but the latest beta crashes with All Hookkit modes (the above was from Cydia substrate only enabled with all bypass options being on).

**Comment by jjolano** [comment]
Looks like they use LIAPP to block jailbroken devices. Shadow currently does not implement anything against LIAPP (at least the newer versions) so bypass-wise the beta is likely to be identical, unless fishhook avoids the potential substrate/substitute checks.

Crashing is likely related to HookKit Framework, so I'll make some adjustments around the actual hook code there.

**Comment by ibrahimqatar** [comment]
Latest beta and Hookkit still crash if you're wondering :P

**Comment by jjolano** [comment]
Are you able to run CocoaTop on Xina? I think I would be interested in an app's "Modules" section, if theres an app that runs successfully with Shadow enabled.

The odd thing about both crash logs is that it doesnt show any information about dylibs related to Shadow, or the tweak injection platform for that matter. So it seems to me Xina has a very strange way of injecting tweaks..

Also, do crashes still happen if you enable Shadow in a crashing app but without any hooks enabled? This will load HookKit, but it can give a hint as to where the issue lies.

**Comment by ibrahimqatar** [comment]
> Are you able to run CocoaTop on Xina? I think I would be interested in an app's "Modules" section, if theres an app that runs successfully with Shadow enabled. Sort the columns by the Size descending (largest to smallest)
> 
> The odd thing about both crash logs is that it doesnt show any information about dylibs related to Shadow, or the tweak injection platform for that matter. So it seems to me Xina has a very strange way of injecting tweaks..
> 
> Also, do crashes still happen if you enable Shadow in a crashing app but without any hooks enabled? This will load HookKit, but it can give a hint as to where the issue lies.

![image](https://user-images.githubusercontent.com/18020735/209855183-1c156ddd-559d-4ffd-818d-2d2283909baf.png)
![image](https://user-images.githubusercontent.com/18020735/209855199-d967793f-f520-4e99-9843-2e8f9ce8f67e.png)
![image](https://user-images.githubusercontent.com/18020735/209855209-f46cba21-3b76-4089-89f9-f905fa54ccc4.png)

For this app, if I enable a hooking library alone, it doesn't crash.
But it crashes with certain combinations, for example:

Enabling File system will crash, but enabling Mach Service Lookups fixes the crash.

Also, having all options on will crash the app? Disabling Dynamic Library only fixes the crash.

**Comment by jjolano** [comment]
Thanks for the screenshots. If you change the hooking library to fishhook, does it still crash the same way? I wonder if the crash log will be different with that.

Also, just to isolate further, let's have only Shadow enabled for the app.

**Comment by jjolano** [comment]
See if HookKit 0.0.7 made any difference. I managed to fix a weird crash on my end but not sure if it applies to Xina.

**Comment by ibrahimqatar** [comment]
On 0.0.7, I still have the same crash on Cydia Substrate but now fishhook crashes from foundation framework, not sure if this was the case with the previous version, can you please enable downgrades?

This test was done with only shadow enabled on the app. But I can't find any crash log in setting after this update (not even with Cydia substrate)

**Comment by jjolano** [comment]
Give this deb a try. This is basically identical to the beta, but does not use HookKit.

[me.jjolano.shadow_3.5-151+debug_iphoneos-arm.zip](https://github.com/jjolano/shadow/files/10318504/me.jjolano.shadow_3.5-151%2Bdebug_iphoneos-arm.zip)

**Comment by ibrahimqatar** [comment]
> Give this deb a try. This is basically identical to the beta, but does not use HookKit.
> 
> 
> 
> [me.jjolano.shadow_3.5-151+debug_iphoneos-arm.zip](https://github.com/jjolano/shadow/files/10318504/me.jjolano.shadow_3.5-151%2Bdebug_iphoneos-arm.zip)
> 
> 

I have the same crash when enabling all options. Disabling dynamic libraries fixes the crash so it's the same case as selecting Cydia Substrate with the previous build.

**Comment by jjolano** [comment]
Thanks, I discovered I made a pretty significant logic error in that hook as part of the changes to 3.5.
This deb should fix it - if it works, I'll update the beta including HookKit and we can see if there are still crashes.

[me.jjolano.shadow_3.5-159+debug_iphoneos-arm.zip](https://github.com/jjolano/shadow/files/10320348/me.jjolano.shadow_3.5-159%2Bdebug_iphoneos-arm.zip)

**Comment by ibrahimqatar** [comment]
> Thanks, I discovered I made a pretty significant logic error in that hook as part of the changes to 3.5.
> 
> This deb should fix it - if it works, I'll update the beta including HookKit and we can see if there are still crashes.
> 
> 
> 
> [me.jjolano.shadow_3.5-159+debug_iphoneos-arm.zip](https://github.com/jjolano/shadow/files/10320348/me.jjolano.shadow_3.5-159%2Bdebug_iphoneos-arm.zip)
> 
> 

Still crashes..

**Comment by jjolano** [comment]
I assume it doesn't happen in 3.4.1? I pretty much compared the two in relation to the hook in question and it shouldn't operate any differently. I'm not sure how Xina really works in regards to handling file paths due to its rootless nature, and Shadow does quite a lot of this.

**Comment by ibrahimqatar** [comment]
> I assume it doesn't happen in 3.4.1? I pretty much compared the two in relation to the hook in question and it shouldn't operate any differently. I'm not sure how Xina really works in regards to handling file paths due to its rootless nature, and Shadow does quite a lot of this.

Just confirmed, it doesn't crash on 3.4.1

**Comment by ibrahimqatar** [comment]
0.0.10 stops the bypass from working..

**Comment by jjolano** [comment]
To be honest, I'm not sure what it can be at this point. Beta works perfectly on both my testing devices at 14.3 and 16.2. It's possible that the Xina jailbreak is mangling some paths in a way that might be affecting the new code, but I have no way to confirm that.

If you are able to get a console log when launching an app using the beta, that might provide some hints as to where I can look closer but I have no guarantees.

For console logs, if you have a Mac you can plug in your device and open the Console.app app. Select your device, start logging, and put "Shadow" in the search box. Launch an app and Shadow logs should appear.

**Comment by ibrahimqatar** [comment]
> To be honest, I'm not sure what it can be at this point. Beta works perfectly on both my testing devices at 14.3 and 16.2. It's possible that the Xina jailbreak is mangling some paths in a way that might be affecting the new code, but I have no way to confirm that.
> 
> If you are able to get a console log when launching an app using the beta, that might provide some hints as to where I can look closer but I have no guarantees.
> 
> For console logs, if you have a Mac you can plug in your device and open the Console.app app. Select your device, start logging, and put "Shadow" in the search box. Launch an app and Shadow logs should appear.

It takes an awful lot of time to load the app and then it still detects the jailbreak. on older beta version, it used to take this much time but at least it bypasses it. now all hooks are not working and the new Dobby is crashing the app.

The log is so long it crashes pastebin when I paste it there so I uploaded it on a text file, please let me know if you are having problems downloading it:

https://1drv.ms/t/s!AsxWRN-xH_D5nShOYIOk3nlbmLWJ?e=2R89Im

**Comment by jjolano** [comment]
Please try it again with the new "Rootless Mode" option in beta 8.

**Comment by ibrahimqatar** [comment]
> Please try it again with the new "Rootless Mode" option in beta 8.

It works now! Everything works as expected now! I will give teams and outlook a go later. I will close the issue, thanks a lot for your effort!!!

**Comment by ibrahimqatar** [comment]
Sorry to reopen this, the bypass for teams works on non-Xina devices but it doesn't here, can I share a console log here so you can have a look?

**Comment by jjolano** [comment]
Can you try turning off "Allow Application Support" and "Mach Service Lookups" and see if it still happens? These are probably the only things I can pick out based on the log.

"Allow Application Support" is only a tweak compatibility option, it technically makes some jailbreak files fully visible for tweaks that need the access. Will be renaming this option though.

"Mach Service Lookups" seems to possibly prevent Shadow from resolving specially crafted paths based on the log. As it's a private API, apps *shouldn't* be using it so disabling the option will hopefully allow Shadow to resolve these paths.

Other than that, the difference is the jailbreak. I'm not really a fan of the Xina jb blindly modifying paths but I guess it is necessary for tweak compatibility.

**Comment by ibrahimqatar** [comment]
> Can you try turning off "Allow Application Support" and "Mach Service Lookups" and see if it still happens? These are probably the only things I can pick out based on the log.
> 
> "Allow Application Support" is only a tweak compatibility option, it technically makes some jailbreak files fully visible for tweaks that need the access. Will be renaming this option though.
> 
> "Mach Service Lookups" seems to possibly prevent Shadow from resolving specially crafted paths based on the log. As it's a private API, apps _shouldn't_ be using it so disabling the option will hopefully allow Shadow to resolve these paths.
> 
> Other than that, the difference is the jailbreak. I'm not really a fan of the Xina jb blindly modifying paths but I guess it is necessary for tweak compatibility.

still the same results, here is the log:

https://1drv.ms/t/s!AsxWRN-xH_D5nWa5dJOVnTxblQ3e?e=AOe8yr

**Comment by jjolano** [comment]
Sorry, I don't think there's much more I can do here for it. The difference is probably just the jailbreak at this point, and it's known to internally modify tweak code for compatibility which can technically produce unintended results. The "rootless mode" option just skips most of the main restriction logic that all other jailbreaks seem to run without issues.

**Comment by ibrahimqatar** [comment]
Fishhook stopped working on Xina in the latest update
