### ISSUE TITLE
More detection items

### ISSUE THREAD

**Issue by maskkit** [jjolano/shadow#84]
Please refer to: [https://github.com/vadim-a-yegorov/Jailbreak-detection-The-modern-way](https://github.com/vadim-a-yegorov/Jailbreak-detection-The-modern-way)

**Comment by jjolano** [comment]
Thanks for the resources. Shadow seems to already handle a majority of this, aside from the bits where the binary itself is modified. I'll see what more I can add, but probably won't support modified binaries.

**Comment by jjolano** [comment]
Implemented a couple of methods in 3.5.1
