### ISSUE TITLE
Crash log for app "Revolut"

### ISSUE THREAD

**Issue by LileAuTresor** [jjolano/shadow#85]
Hi,

On the recent update of [Revolut](https://apps.apple.com/fr/app/revolut-la-banque-en-ligne/id932493382) (8.85.1), shadow crashes. 
I tried with all possible combinations of hooks without success. Version 8.80 works fine with essential hooks enabled.

I'm on IOS 13.5 with Unc0ver, substitute 2.3.1 and Shadow 3.5-1. 

Here is the crash log : https://pastebin.com/CZVvdrfp

Please watch if you have time

Edit : Shadow 3.4.1 works... I looked on Effulgence what was detected following the update of Shadow in 3.5, there are many more things than in version 3.4.1...

On 3.5:
- Writable Root Filesystem
- Injected Libraries
- Runtime modification 
- Code Injection Platform
- Shadow

On 3.4.1 :
- Runtime modification 
- Shadow

**Comment by jjolano** [comment]
Interesting.. it looks like hooks aren't working. It's likely related to HookKit Framework, but not sure since the app launches fine without the detection notice on my 14.3 and 16.2 devices with Shadow enabled.

Can you try opening Effulgence with the fishhook hooking library (and all options except compatibility)?

**Comment by LileAuTresor** [comment]
With fishhook hooking library Effulgence doesn’t detect artifact. 
The app Revolut is OK with this hooking library and essentials + recommended hooks activated.  
Maybe substitute hooking library doesn’t work as it should ?

**Comment by jjolano** [comment]
Yes, seems like the substitute library isn't working properly. That part is handled by HookKit Framework, so I will be taking a look there.

If you want to match 3.4.1 behaviour, try using Cydia Substrate as the library.

**Comment by LileAuTresor** [comment]
I'll keep the fishhook library for now, my apps seem to work.
Don’t hesitate to come back to me if you need to test a fix for the substitute library.

**Comment by LileAuTresor** [comment]
Can you reopen this issue, Shadow doesn’t work on 8.87 update of Revolut. 
I have all hooks activated with fishhook library (no artifact detected on Effulgence with these settings). 
The app doesn’t crash but doesn’t pass the faceid authentication page. 
On previous version 8.86 all was OK...

I’m on Shadow 3.5.6 and HookKit Framework 0.1.7
