### ISSUE TITLE
Mbanking DANA Crashes when turn on essential hooks,IOS 16.1.2 Palera1n

### ISSUE THREAD

**Issue by rijiq123** [jjolano/shadow#86]
On ios 15 DANA works well with shadow jb bypass ,and it crashes on ios 16

**Comment by jjolano** [comment]
Substitute likely has issues on iOS 16. Try changing the hooking library to fishhook or Dobby.

**Comment by rijiq123** [comment]
> Substitute likely has issues on iOS 16. Try changing the hooking library to fishhook or Dobby. Not much I can do otherwise.

Thank you so much , it works
