### ISSUE TITLE
Update to new version

### ISSUE THREAD

**Issue by D1mar0n** [jjolano/shadow#87]
One of the updates was not found in your repository. Please correct. 

![D9613380-FBF9-4965-8BE9-EC3877D014A3](https://user-images.githubusercontent.com/35725771/211186670-ef07e0a1-63c1-4efd-b0ad-039955de1167.jpeg)

I also want to ask you to add support for CaixaBank Sign if possible. This application does not want to start without any settings in Shadow. I used to use Unc0ver 8.0.2 / iOS 14.2, now I'm on Taurine 1.1.6 - I can't run this app either. If you need additional information, please write.

**Comment by jjolano** [comment]
Please refresh sources and try again. As for the app, I have no guarantees but maybe my current methods will develop enough to support it later on.

**Comment by D1mar0n** [comment]
Thank you very much for your reply! This application is very important to me, because without it it is impossible to confirm any of the banking transactions. I would be very grateful if you could check its performance on your devices. This will help me understand where to look for a solution to the problem: the problem is iOS damage or just need to wait for a new bypass method in your tweak. Thank you in advance for your response.

Enviado desde iPhone

**Comment by budakcivic** [comment]
Hi jjolano, may I know why same apps version and tweak version but on ios14 ok not detect but on xina A15 the jailbreak detected?

**Comment by jjolano** [comment]
> Hi jjolano, may I know why same apps version and tweak version but on ios14 ok not detect but on xina A15 the jailbreak detected?

#80

**Comment by jjolano** [comment]
Will close this for now as the original issue (updating) should be resolved.
