### ISSUE TITLE
Jailbreak detection on Revolut 8.87

### ISSUE THREAD

**Issue by LileAuTresor** [jjolano/shadow#88]
Hi,
I open again an issue for jailbreak detection on the app Revolut version 8.87.
I have all hooks activated with fishhook library (no artifact detected on Effulgence with these settings).
The app doesn’t crash but doesn’t pass the faceid authentication page.
On previous version 8.86 all was OK...

I’m on Shadow 3.5.6 and HookKit Framework 0.1.7

Can you look please ?

**Comment by jjolano** [comment]
I do not use the app, so unfortunately I can't verify anything.
Also, just to reiterate there is nothing app-specific within Shadow so there is likely nothing I can do about it unless a hook has a buggy implementation

**Comment by LileAuTresor** [comment]
OK, it’s strange, it works again with HookKit Framework 0.2...
