### ISSUE TITLE
Last version doesnt works with banks

### ISSUE THREAD

**Issue by PONCE54958** [jjolano/shadow#89]
The last versions doesnt works with mexican banks, only version 3.4.x works fine, could you check it please? already try all ways enabling and disabling multiple combination between features and subtitute, substrate etc.. 

Apps: bbva mexico, hey banco

**Comment by jjolano** [comment]
It only works with 3.4.1? Can you try with the beta version and check the option `Enhance Path Processing` for the apps?

**Comment by PONCE54958** [comment]
now works
![93E1898F-5CE4-4290-93E0-F1E2EB5CEDB9](https://user-images.githubusercontent.com/36983248/212552580-82efa879-26a6-45cd-b778-1ecefd389a8c.png)

I have only this options enabled, works now on hey banco and bbva
