### ISSUE TITLE
Jailbreak still get detected by some apps.

### ISSUE THREAD

**Issue by Liam0205** [jjolano/shadow#90]
Some apps on my iPhone still detect jailbreak status with Shadow enabled. Please kindly help me to investigate further.

## Environment

* iPhone Xr
* iOS 14.5.1
* Unc0ver 8.0.2
* Shadow 3.5.6

## Shadow Configurations

* Always-on: false
* Bypass Settings:
  * Hooking Library: Automatic
  * Allow Tweak Resources: false
  * Enable Rootless Mode: false
  * Essential Hooks
    * File System: true
    * Dynamic Libraries: true
    * URL Handlers: true
    * Environment Variables: true
  * Recommended Hooks
    * Detection Frameworks: true
    * File System (tExtra): false
    * Foundation Framework: false
    * M1Mac (iOS 14+): false
  * Following settings are all set to be false

### HSBC HK

* Introduction: Mobile bank app for HSBC HK.
* AppStore: https://apps.apple.com/us/app/hsbc-hk-mobile-banking/id1164066737
* Without Shadow: App crashes almost immediately (in seconds), after tap on its icon.
* With Shadow (same settings with global): App crashes in seconds, after tap on its icon.
* What I've tried: different Shaodw settings (including `fishhook` library), disable all other tweaks by Choicy, reboot and try again (since Unc0ver)

### HSBC China

* Introduction: Mobile bank app for HSBC, mainland China
* AppStore: https://apps.apple.com/us/app/%E6%B1%87%E4%B8%B0%E9%93%B6%E8%A1%8C/id1217785007
* Without Shadow: App crashes almost immediately (in seconds), after tap on its icon.
* With Shadow (same settings with global): App crashes in seconds, after tap on its icon.
* What I've tried: different Shaodw settings (including `fishhook` library), disable all other tweaks by Choicy, reboot and try again (since Unc0ver)

### 交通银行

* Introduction: Mobile bank app for bankcomm
* AppStore: https://apps.apple.com/us/app/%E4%BA%A4%E9%80%9A%E9%93%B6%E8%A1%8C/id337876534
* Without Shadow: App crashes almost immediately (in seconds), after tap on its icon.
* With Shadow (same settings with global): App crashes in seconds, after tap on its icon.
* What I've tried: different Shaodw settings (including `fishhook` library), disable all other tweaks by Choicy, reboot and try again (since Unc0ver)

### 北京一卡通

* Introduction: the app to manage NFC transportation cards of Beijing.
* AppStore: https://apps.apple.com/us/app/%E5%8C%97%E4%BA%AC%E4%B8%80%E5%8D%A1%E9%80%9A/id1071038870
* Without Shadow: App crashes almost immediately (in seconds), after tap on its icon.
* With Shadow (same settings with global): App crashes in seconds, after tap on its icon.
* What I've tried: different Shaodw settings (including `fishhook` library), disable all other tweaks by Choicy, reboot and try again (since Unc0ver)

---

Any clues will be appreciated. If you need any more information, please let me know.

**Comment by jjolano** [comment]
Thanks for the detailed issue, I appreciate it. Unfortunately with Shadow's design it does not handle anything app-specific, only more general to apply to the most apps overall. Some apps (especially high-security ones like banking) have their own way of detecting which I yet to have developed a workaround for. If you have already tried all that Shadow has to offer, those apps may need a bypass more specific to the app.
