### ISSUE TITLE
Supercell game settings

### ISSUE THREAD

**Issue by Drizzle2002** [jjolano/shadow#91]
Does anyone know what settings I should use for supercell games like clash of clans, clash royale, etc? I am using the default settings and all of the apps just crash after a few seconds. 
Im on ios 15.0 using xina jb on iphone 12.

If anyone can help thx

**Comment by jjolano** [comment]
This isn't a public forum. For questions like these, I suggest asking on the jailbreak subreddit or discord.

Those games have injection detection rather than jailbreak detection, so it's likely the way around it is to reboot into unjailbroken state or maybe use that built in bypass that Xina has.
